---
title: "R Notebook"
output: github_document
---

## Load Packages and Data

```{r}
library(tidyverse)
library(RColorBrewer)
library(scales)
getwd()
Pokemon <- read_csv("Pokemon.csv")
theme_set(theme_minimal())
```

## Visual Pokemon By Distribution by Type

Color Selection was based on in game graphics via [this photo](https://vignette.wikia.nocookie.net/robloxpokemonbrickbronze/images/5/5f/Type.png/revision/latest?cb=20170426085006)

```{r}
Pokemon %>% 
  group_by(`Type 1`) %>% 
  mutate(Type = `Type 1`) %>% 
  ggplot(aes(x = factor(1),fill = Type))+
  geom_bar(width = 1)+
  coord_polar(theta = "y")+
  theme(axis.text.x=element_blank())+
  labs(x = "", y="", title = "Pokemon Visualized by Primary Type")+
  scale_fill_manual(values=c(	"#89970E",	"#000000",	"#765EE1",	"#E79302"	,"#F5B0F5"	,"#601500",	"#C72100",	"#5D73D4",	"#5D5DB2", "#0E7B00","#D3B356",  "#6DD3F5", "#7F6F65", "#47004A", "#E72062", "#9E863D", "#9B9BAB", "#0061BE"))





```

```{r echo=FALSE}
                  Color   <- list("Grass" = "#0E7B00", 
                             "Fire" = "#C72100",
                             "Water" = "#0061BE",
                             "Bug"= "#89970E",
                             "Normal" = "#7F6F65",
                             "Poison" = "#47004A",
                             "Electric" = "#E79302", 
                             "Ground"  = "#D3B356",
                             "Fairy" = "#F5B0F5",
                             "Fighting" = "#601500",
                             "Psychic" = "#E72062",
                             "Rock" = "#9E863D",
                             "Ghost" = "#5D5DB2",
                             "Ice"= "#6DD3F5",
                             "Dragon"= "#765EE1",
                             "Dark"  = "#000000", 
                             "Steel"= "#9B9BAB",
                             "Flying"= "#5D73D4")
```

