---
title: "kaggle"
output: pdf_document
---

1. Kaggle competition - Titanic: Machine Learning from Disaster
Goal:
The sinking of the RMS Titanic is one of the most infamous shipwrecks in history.  On April 15, 1912, during her maiden voyage, the Titanic sank after colliding with an iceberg, killing 1502 out of 2224 passengers and crew. This sensational tragedy shocked the international community and led to better safety regulations for ships.
One of the reasons that the shipwreck led to such loss of life was that there were not enough lifeboats for the passengers and crew. Although there was some element of luck involved in surviving the sinking, some groups of people were more likely to survive than others, such as women, children, and the upper-class.
In this challenge, the goal is to complete the analysis of what sorts of people were likely to survive. In particular, apply the tools of machine learning to predict which passengers survived the tragedy.

For submission:
I need to use knowledge of Binary classification and Python and R basics to come up with the analysis and statistics. I will submit a csv file with exactly 418 entries plus a header row.  The file should have exactly 2 columns: Passengerid (sorted in any order); Survived (contains your binary predictions: 1 for survived, 0 for deceased)

