---
title: "MACS 30000 Assignment 1"
output: pdf_document
author: Li Ruixue
---

## Research question: 

How much of the business activity on *Taobao* is genuine and how do the fake purchases and reviews affect real sales. 


Taobao is the biggest C2C and B2C e-commerce platform in China with millions of active users and billions of revenue. (WIRE 2017) However, most sellers and experienced users know that not all business activities there are genuine. Two common cases are fake buyer reviews and fake transactions created buy some sellers or entities hired by them. Though there are official channels for businesses to advertise their products like buying ads on the homepage, those are costly and consumers tend to trust information generated by other users more. Therefore, in order to survive the intense competition on Taobao, some sellers resort to methods such as making purchases of their own products to create artificially high volume of sales and posting positive comments for themselves. Many of them even pay other people to conduct these activities. 

While this phenomenon is hardly unique to Taobao, it's becoming a real concern for many consumers. Meanwhile, business partners, competitors, market observers, and even Taobao itself would probably like to have a better idea of the real level of business activity on the site, as the information may affect their investment decisions or business strategies. Therefore, I believe that finding out the amount of purchases and reviews that are fake, as well as how these seller-generated purchases and reviews affect the behavior of real buyers will be an interesting and meaningful research. More specifically, I'd like to find out what percentages of transactions and reviews are produced by sellers for the sake of making their products look more appealing, and to quantify the amount of real sales produced by these fake transactions and reviews. 

##Data source:

There are two sources of data that we could potentially use. The first one will be data collected by the Taobao platform itself, which should include detailed user (both buyer and seller) profiles, product information, transaction details, reviews, and information on advertisement and promotions. The second one is scraping data from the site, and the information gathered will be limited to publicly available user, product, transaction, and review information.

##Methodology:

The first and step in answering these questions is to find a way to differentiate fake and genuine contents. This is definitely a complicated question that requires a lot of research and advanced algorithms in fields such as natural language processing, but I think that the following approaches are a good starting point: 

1. To identify fake reviews, we could:

a) Look at all the reviews posted by a user. Since a seller or a professional fake review poster will likely post many reviews of similar (positive) content, on similar products, or at a high frequency, while normal users usually only make purchases and post reviews on a range of products at irregular frequencies, these characteristics could be used to different fake reviews.

b) Look at all the reviews under a specific product. If there's a suddenly spike in the amount of reviews a product receives and the reviews are all of similar and positive content, then it's likely that the seller has arranged for some professionals to post the reviews. 

2. To identify fake purchases, we could similarly:

a) Look at all the purchases made by a specific user, since a seller or a professional fake buyer will likely buy many of a particular product or at a high frequency in order to boost the rankings of some products.

b) Look at all transactions under a specific product. If there's a suddenly spike in the amount of sales, then it's possible that the seller has arranged for that to happen.

However, since advertisements may also cause a sudden increase in sales, it'll be better if we could rule out that possibility by combining the methods mentioned above with information on past advertisements. 

Meanwhile, identifying fake users will also be useful since most of the fake activities are done with those fake accounts. These users may be relatively easy to find since they tend to have features such as long and meaningless username, a large number of similar purchases and reviews generated within a short period of time, and many of them can even come from a same IP address. In the end, the fake contents need to be identified by using a combination of the methods above. 

Once the fake purchases and reviews are identified, their number and transaction amounts can be calculated and conclusions could be made, such as their percentages in the total sales and number of reviews in each product category. 

The second part of the research question is to measure the effect of these fake transactions and reviews. I think that this goal will be best achieved by using matching. Since on Taobao, there will usually be multiple sellers who sell the exact same product using the same descriptions they obtained from the manufacturer, and Taobao has an existing algorithm to identify those products, we can find products that are very similar in all aspects such as product description, price, and rankings in an organic search, except that some of them received fake reviews or purchases. Once we identify these pairs, and if we control for other factors such as whether the seller has advertised the products and how long the listing has been active, theoretically, we could quantify the effect of the fake reviews and purchases by looking at the difference in their sales. 

##Discussion on using big data:

Since Taobao is a huge marketplace with an enormous amount of information, this research will involve big data. And this is beneficial because while fake reviews and purchases are not unusual, they are definitely not the majority, and any algorithm of identifying them will surely be imperfect. Therefore, it's good to have a large population available so that we can find a big enough sample even if we want to make the criteria very strict in order not to include real review and purchases by mistake. A large amount of data will also make observations by product category possible. Also, with big data, we are more likely to find perfectly matched pairs in the second part. Besides, sellers and users on Taobao are unlikely to react in any way since this approach is purely observational. 

However, one of the biggest challenges of this research lies in the inaccessibility of data. Taobao probably won't appreciate the findings that their record sales volume is bloated or their customers knowing that the reviews they are seeing could be fake, so they may not be cooperative in providing the dat. This challenge needs to be met with negotiation and compromises, with researchers convincing the company that a research like this could benefit them as well by providing insights on their business and helping them improve their platform. 

There are also other problems related with big data that we'll need to address:

1) Incomplete: The data may not be complete if we're unable to obtain the records from the company and could only scraping data from the website, since the product listings can be deleted by the sellers. Also, we may not have access to certain attributes such as IP address of the users if the platform doesn't track that information in the first place. Fortunately, since our dataset is big, this problem isn't likely to have huge impact since we'll be able to find enough of other information to measure our targets.

2) Drifting: sellers and fake review posters are constantly improving their techniques to emulate the real reviews, therefore making them harder to detect over time. To counter this problem, our detection algorithm needs to take into account of these changes in behavior and combine with human inspection of the identified fake reviews and purchases to increase accuracy.

3) Algorithmically confounded: Taobao has a sophisticated mechanism for searching, recommending, and advertising products, which are likely to change consumer behavior. This can be mitigated by limiting our data to a subset that these algorithms are not applied, such as those products that didn't participate in time-limited sales.

4) Dirty: Since there are a lot of different types of information we can collect on Taobao and people use and behave on this web in very diverse ways, the data may be messy and dirty. The best way to avoid this problem as much as possible may be identifying the attributes and users that are relevant to the research, and limit our data collection. 

5) Sensitive: While data collected in this research could include personal information, but they are not what really matters because Taobao users can be identified by their usernames which are public, and other demographic details are not relevant and therefore need not be collected nor published.
  
All in all, I think that Taobao is a huge data repository that we can derive some great insights from, and the questions proposed in this paper are among them. While difficult, this is a research that can be done, and the method can even be generalized to other online shopping sites in the future. 

###Bibliography

WIRE, BUSINESS. 2017. "Alibaba Group Announces June Quarter 2017 Results". Businesswire.Com. http://www.businesswire.com/news/home/20170817005472/en/Alibaba-Group-Announces-June-Quarter-2017-Results/?feedref=JjAwJuNHiystnCoBq_hl-fZYqiffDpHIASjea2DwvsWD1w08bW43U_zsPK9s38B4rCOi9QzgjCezTS3Nw_X6kJUrpSBm-Hav1w-UkdSlG3nBCddZ7R8TUqSJPYIyhFzD7nKdfLXU1CD0fwzlM5l88g==.
