---
title: "Biagioli- Observations Paper"
author: "Rita Biagioli"
date: "October 21, 2016"
output: html_document
---

###You should (briefly) explain your topic of interest and the specific question you seek to answer in this research project. 
Globalization theorist Arjun Appadurai discusses the ways in which media of all sorts (newspapers, movies, etc.) serve as reflections of the worlds they attempt to represent, but, simultaneously, through their dissemination and consumption, affect that represented world, thus imagining and reifying the way things are. This process occurs continuously; we act and consume and act and consume. With the spread of internet access and the ability to share media globally, we affect and are affected by each other with so much frequency and alacrity and with differing magnitudes and directionalities that it is difficult to take positions regarding causality. 

In India in particular, consumption of Western media has been on the rise for years. Abandoning joint-family structures, where many members of a household live together, young Indians are setting out on their own and are living more Westernized lives: women are working, young people are living alone, and dating culture is flourishing. However, in a society where arranged marriage was perceived as the only permissible means of coupling for thousands of years, the structure of romantic interactions and how they are initiated, milestoned, and discontinued is still being built by young Indians. 

Though it is, from a practical standpoint, extremely difficult to measure the ways in which media affects behavior, particularly in relation to something as potentially private as dating, it is certainly possible to impute the effects of media on resulting discourse online, and, moreover, how that discourse feeds back into the production of media. **(Research Question:)** To this end, this study seeks to better understand how the iterative relationship between media and the discourse on social media in India serve to constitute and inform each other’s renderings and definitions of love and dating.

###Next, identify the basic research design you will undertake (e.g. counting things, measuring something, forecasting, natural experiment, matching) and the source of the data. 
In order to conduct this research, I will analyze data from two sets of sources. First, I will look at media in the form of online news, movies, and TV shows. I will determine which media to explore given levels of popularity, for which I will have to find a metric; said metric will likely relate to counting something, such as views or downloads. Through this measure, I will be able to reconstruct a picture of the media that an average Indian with internet access might consume. This media would also include particularly relevant global sources, given that, in particular, Indians are also avid consumers of American movies and American and British news. A complete repository could potentially also make reference to DVD sales,1 illegal downloads, and Neflix views, if available.

Once I’ve identified relevant sources, I will construct a cluster of words often used when discussing dating, love, romance, etc, and will compile relevant passages into a database. Such a database would also include movie and TV transcriptions, as well as some potential translation into either Hindi or English. Additionally, I would scrape the date of production as well as dates of consumption (e.g. number of people who viewed a movie on a given day). After all of this data is compiled, I would create a program to do a linguistic analysis of the particular terms and subjects in question.

Second, I would collect whatever comment data was publicly available on popular Indian social media sites, such as Facebook, Instagram, Twitter, and Quora. In an ideal world, I would have access to WhatsApp data, but that is unlikely to actually occur. If possible, I would attempt to determine the approximate age of the poster, and would also collect the date of the post. I would create a second cluster of words and topics and would compile relevant passages. Moreover, I would see how this cluster correlates with that of the media sources. I would then apply the cluster from the media sources to the social media data and vice versa.

With all of this linguistic data, I would be able to map how the discourse surrounding dating, love, and intimacy has changed over time as well as where these instances correlate or diverge. In particular, I would use various forms of linguistic and sentiment analysis (Liu). Which media sources seem to affect how people talk on social media and in what ways? What about what these people say is affected? Can we discern any particular definitions or trends and, most interesting, is there a causality to be observed in either direction over time? What about the interaction of media and discourse is iterative and what is not?

Ideally, I would run this study for several years in order to observe any societal change, though I believe that certain affects would be discernible relatively quickly. Moreover, I would ideally run this study in multiple countries in order to compare the ways in which culture interacts with media as well as the ways in which culture affects how people interact with media. For the purposes of this paper, however, I am focusing primarily on India. Contemporary India is, in a way, a natural experiment because what it means to date and be in love is changing so rapidly, allowing potential causal conclusions to be drawn in a shorter period of time. Young Indians are constructing a system from the ground up, and, as a result, trends morph quickly.2 This level of ambiguity leaves room for first, people to ruminate publicly, and, second, the possibility of elucidating the relationship of media to culture through it’s potentially greater affect on unfixed, flexible, and alterable norms and definitions.

###The bulk of your proposal should be a critical assessment of why you believe this project will be a good example of digital research.
The proposed research could not be conducted without the aid of big data. First, a massive number of data points is necessary to detect any relatively small shift in the ways in which people talk or the way media constructs itself. Second, the contemporary nature of media and social media is such that continuous data can be collected, and for a study which depends upon small fluctuations over continuous periods of time, this is imperative. Third, it would take mere humans a massive number of hours to even approximate the work of a program in this case. Though humans could create linguistic codes, and though some of the data and coding should be double checked by people, examining a sample size this big would almost necessitate human error. Fourth, the data collected are certainly non-reactive; media is made for consumption and is, to some extent, fixed once it is published or produced. People on social media will not know they are being observed. Because the only data needed are posts and relative ages, and because the population being examined is all of India, it would be possible to only look at public Facebook pages, for example, and to maintain anonymity by eliminating all identifying information from posts; there is no reason to assume that this sample is significantly different than others who keep their profiles private. If anything, perhaps this sample would be somewhat less technologically literate, but that does not affect the object of study in this case.

This study could not be conducted without big data, and could potentially provide significant insights on the flow of information and mediascapes, as Appadurai calls them. There are, however, limitations to this study. Though the data will be anonymized, it is sensitive to some extent since there will be no informed consent and there is the possibility that a post on social media could be recognizable. I would assume that an IRB would sign off on this study given that it would only make use of what is publicly available, but there is always the possibility of discontent. This is an issue that will likely remain unresolved, but is one to be cognizant of.

It is possible, additionally, that some data will be inaccessible and/or incomplete, particularly information from Netflix and WhatsApp or data on the ages of people on social media. This data, however, is not imperative to the crux of the study. While it would be significantly supplemental, the study could still go on if this data is not available. Age specifically is somewhat easier to infer: young Indians are far more likely to use social media than older Indians. Given that this is the population that will likely produce the most fruitful results, the fact that this sample is non-representational in this way is less of a problem. However, one issue to note with regard to representation is that this sample will necessarily be in a higher socioeconomic bracket, given that having the internet is necessary to use social media sites. Though smart phones are more and more common, they still aren’t pervasive in India. Again, however, this study aims to look at how consumption of media, largely online, affects what people say online, and also attempts to reflect upon changing dating structures; people in India who have access to internet are the same people who are likely to have changing ideals of romance.3 This is, indeed, a bit of a study of the elite, as it morphs from an ethos entirely Indian to one globally melded by media.

Since constructs will be constructed from the data itself and then compared against measures of love, dating, and intimacy that social psychologists have been using for years (see the work of Eli Finkel and Paul Eastwick, for example), all possible precautions regarding validity will be taken. From my experience, Indians do often talk about these issues online, and therefore there would be significant data to make use of. As per drift, in some ways this study is a measure of drift itself, and will need to constantly re-evaluate what forms of media are popular and where people are discussing their lives online. So long as these measures are kept up to date, most problems with drift should be accounted for and, in fact, interpreted.

Part of the beauty of this study is that its flexibility makes it feasible. It makes significant use of publicly available data and popular media, which is meant for consumption. The collecting of disparate data and the monitoring of differing levels of consumption would be rather difficult, but not impossible. There is also the possibility that a given social media site would not allow this type of data-gathering, but there are several social media sites that could serve a similar purpose in this instance. One potential feasibility issue is the use of language. Many Indians do in fact prefer to post on social media in English, and it is actually their preferred language. When they do use other languages, however, these languages are often transliterated into Roman script inconsistently and spelling is inconsistent. Significant efforts might need to be made to discern what is being said. Additionally, translation is an imprecise process, and communicating certain concepts in different languages is difficult; it might be hard to perfectly correlate what is being said in English with what is being said in Hindi. Some method of image analysis would also need to be devised, given that memes are a popular mode of communication. However, while I believe these are potential deficiencies of the study, I do not believe that they are insurmountable. Assessing the waves of media and social discourse with regard to love and intimacy in India could highlight something more profound about the waves of media and social discourse themselves, and could significantly affect the ways in which scholars understand the effects of media and its consumption on the lives of individuals.


Appadurai, Arjun 
	1996 Modernity at Large: Cultural Dimensions of Globalization. Minneapolis; London: University of Minnesota Press.

Liu, Bing
	2012 Sentiment Analysis and Opinion Mining. 
