---
title: "Proposing a Survey Study"
author: "Kristopher Nichols"
date: "October 23, 2017"
output: html_document
---


##Introduction:
As research continue to reveal that the majority of American citizens support government intervention in limiting carbon output and support of climate change policy, social scientists have sought to discover what t creates the discrepancy between these polls’ results and election [results.](http://climatecommunication.yale.edu/publications/more-americans-perceive-harm-from-global-warming-survey-finds/) This line of research covers a multitude of disciplines, and  psychology in particular has a great amount of potential to provide answers due to its ability to investigate and describe personality traits with scales and measures. However, with the fickle way in which participants answer surveys – whether it be on account of reactance, framing effects, observer-expectancy bias (when a participant may feel pressure to yield a certain result and acts accordingly), or  several other biases – these studies should be taken with a measure of doubt. These types of measures are incredibly susceptible to biases and error that can be particularly damaging in the context of climate change research. 
Adding computational elements - particularly ecological momentary assessment (EMA) elements - can help to control for some of these biases. For example, this method’s ability to work in questions to organic and salient situations can provide much more accurate representations of attitudes and traits. The EMA approach allows for new light to be shed on not how participants view the problem of climate change as foreign or distant, (the current dominating approach in psychological research on climate change) but how individuals react when they are confronted with the real consequences of climate change. In an applied sense, to measure how participants react to large discrepancies between normal temperatures and temperatures much higher or lower than they should be on a given day may affect their belief in climate change. Secondly, these EMA elements allow for measurement of longitudinal data, compounding the advantage of salient situations over many different observations. This would allow for measurement of multiple instances of large weather discrepancies for comparison across seasons. With these advantages the measurement of participants’ attitudes towards climate change can be tracked as different situations arise, potentially shedding light on what traits inoculate against, or mediate, climate change attitudes. 

###Research Question:
How do large discrepancies between “normal” temperatures for a given day, and actual temperatures affect participants attitudes towards climate change?

##Design:
There are several important aspects involved in employing a successful EMA approach, including: software used to display the surveys, the scales actually used during the experiment, the need for any other software to actually measure or keep track of the “momentary” situation (i.e., what software will be used to measure these discrepancies in weather), and with what technology will the research be utilized. Regarding the issue of survey software, the principal concern is the possibility of being limited in survey construction by survey software companies such as Qualtrics, Survey Monkey, and others, and in this case this is not a very salient worry due to this study’s use of classic Likert or Boolean surveys. Although, a limitation I am accepting in using these sites is that the device on which the survey appears must be connected to the internet. The New Ecological Paradigm (NEP) scale, a scale which measures endorsement of “pro-ecological world view” that is scored on a four point Likert scale, will be utilized as the central dependent variable for this [study](http://journals.sagepub.com/doi/abs/10.1177/0013916595276001). Other scales that will be included are the suite of questions utilized by the Yale Project on Climate Change Communication site, which are used to test knowledge of climate change and includes questions such as “how sure are you that global warming is [happening?”](http://climatecommunication.yale.edu/publications/Americans-knowledge-of-climate-change/) These questions will be programmed to arise should instances of temperatures more than two standard deviations away from the mean temperature occur; this number of SDs vetted by Dr. Allen of Oxford as the threshold after which “it could be argued that the event would never have occurred without a certain level of background [warming](https://blogs.shell.com/2012/04/05/extreme/)". Although this strict definition could be potentially limiting for data collection, this ensure more external validity.  
The EMA software used to display questions should certain weather conditions arise is largely already present in the “ilumivu” software package, and this type of weather based EMA research has been utilized in studies [before](https://ilumivu.com/about/science/).  However, further coding will likely be necessary due to the limit of the weather applications, and this may limit this study’s ability to use pre-existing software and may mandate creation of software – a potential limitation to this study. Another potentially costly aspect to this study is the possible need for devices. Although many EMA software developers have created phone applications for their software, there is potential that new devices may have to be bought to supply to participants, a major limitation due its extremely high cost. *In summary, this study will utilize an independent variable of weather discrepancy versus no-weather discrepancy design with the central outcome variable being the New Ecological Paradigm Scale.* The weather discrepancy condition is defined as participants exposed to temperatures two standard deviations away from the mean temperature, while the no-weather discrepancy condition is defined as participants exposed to weather within the two standard deviations of the mean. Participants will be given devices or directed to use applications which are programmed to display questions based on their randomly generated condition. Researchers will attempt to make use of a combination of already developed survey software with possible use of “ilumivu” EMA software to display the questions based on weather. However, the potential exists for the need of specifically created programs, as noted, a potential limitation. 

##Advantages and Disadvantages:
Ecological Momentary Assessment methodology offers a bevy advantages over traditional surveying methods, as its flexibility allows for answers that are more likely to be externally valid and precise. Due to the outcome of discovering under which circumstances individuals are most – or least – inoculated against climate change beliefs, the ability to note context is absolutely pivotal. Whereas in traditional survey methods the participant is put in blatantly artificial environments with multiple potential biases, potentially resulting in self-monitoring, this method reduces these effects.  It could be argued that in a scientific environment the pressure to conform to opinions that are more scientific would be an especially salient bias in this line of research – a large limitation for all survey based research regarding sensitive political attitudes. This approach also reduces the effects of memory bias, in that the temporal distance between a participant experiencing a stimuli and answering questions regarding their feelings on the stimuli is ideally non-existent. Furthermore, the EMA approach also yields benefits even compared to other computational approaches. In the last proposed study, which utilized a natural experiment design, the context could never be completely known to the researchers. Although matching principles were adopted to alleviate concerns regarding context, the context cannot be known as sufficiently as it can be noted and controlled for in the instance of EMA research. While this method involves significantly more individuality and organicity, it also involves significantly more literal costs and some disadvantages as well. Firstly, the EMA approach is still likely subject to psychological reactance on behalf of the participant. It could be argued that the participant may be more likely to experience reactance due to the ever present feeling of being observed. Secondly, the problem of attrition, and consequently, decreasing quality of data is very salient in this approach. All sources of data are subject to participants willingness to regularly complete their surveys, and researchers have noted that participation can decline after 2-3 weeks of data [collection](https://link.springer.com/chapter/10.1007/978-90-481-2354-4_8). However, this can be combatted through the use of filler day-to-day tasks to keep the participant focused and habituated, especially since the recording of data may be more sparse. Lastly, the issue of technological knowledge biasing data is very salient, as with all EMA designs. It could be argued that this concern is especially salient here as those that are the least technologically proficient may be a population that is most unfamiliar with climate change research, potentially biasing the data. However, a teaching session at the beginning of the study can be utilized to decrease the learning curve and hopefully have participants on a somewhat even starting place. 



```

