---
title: "Propose an Experiment"
author: "Kristopher Nichols"
date: "October 30, 2017"
output: 
  html_document:
    theme: readable
---
##Introduction
As research continue to reveal that the majority of American citizens support government intervention in limiting carbon output and support of climate change policy, social scientists have sought to discover what t creates the discrepancy between these polls’ results and election [results.](http://climatecommunication.yale.edu/publications/more-americans-perceive-harm-from-global-warming-survey-finds/) This line of research covers a multitude of disciplines, and  psychology in particular has a great amount of potential to provide answers due to its ability to investigate and describe personality traits with scales and measures. However, with the fickle way in which participants answer surveys – whether it be on account of reactance, framing effects, observer-expectancy bias (when a participant may feel pressure to yield a certain result and acts accordingly), or several other biases – these studies should be taken with a measure of doubt. These types of measures are incredibly susceptible to biases and error that can be particularly damaging in the context of climate change research. Furthermore, the experiments which employ these measures threaten their ability to truly determine causal mechanisms due to the biases introduced by inadequate external validity. 

This is a problem handled extremely well by research designs enhanced by computational elements, and in particular, experimental designs. Experimental designs enhanced by computational elements utilize the power of imposing causality combined with the inherent benefit of greater external validity that big data provides to achieve great benefit. This is extremely important to confidently reveal underlying mechanisms and this is a problem that the experimental design handles with greater ease, even compared with other digitally enhanced research designs. For example, while observational designs may be able to access the sheer bigness of big data and leverage its benefits of external validity, it is not able to completely impose causality – even natural experiment designs demand matching principles which leave researchers open to selection biases. And enhanced surveys also suffer from problems in imposing causality, sacrificing some levels of internal validity due to canned responses. Experimental designs leverage the benefits of both of these designs. These designs can shed light on what mechanisms underlie individuals’ disbelief in climate change, how they react when confronted with different types of information supporting climate change, and with carefully thought out groups, how different types of people interact with this information. Due to the potential information that added external validity and heterogeneity of groups may shed on the mechanisms that inoculate individuals against climate change an experimental design would be very beneficial here. 

###Research Question:
How do individuals react to confrontation on their climate change disbelief when the confronter is of similar political ideology, different political ideology, and presents information that is empirical or anecdotal.

## Design:
The study will draw upon elements of the work done by Munger [(2017)]( https://link-springer-com.proxy.uchicago.edu/article/10.1007%2Fs11109-016-9373-5) and utilize Twitter as a data base. The study will utilize Twitter data using the SteamR package in R Studio to scrape Twitter data for tweets towards government run weather-related twitter pages which disparage climate change. These disparaging comments that will be scraped will include negative words such as “lying” and “untrue”. Tweets marked by the scraping will then be traced back to the user in which the user’s last 1000 tweets will be scraped for other tweets disparaging climate change and scored in relativity to the number of tweets. The scoring threshold will be calculated by taking a random sample of Twitter users and calculating their rate of derogatory climate change remarks. 

After this is completed, users who score appropriately high for inclusion in the study will then be assigned to one of the six possible conditions. *The study will use a 4x2 research design with conditions dictating what type of bot will be prompted to reach out to participants and with what type of information (see table at end of document).* The bot will either feature *Democratic or Republican political ideology* in its bio, pages that it is following, and its most recent tweets.  Furthermore, the bot will respond to a derogatory tweet towards climate change with *information of either anecdotal content (i.e., the story of someone affected by weather in which a climate change hypothesis is invoked) or empirical content (i.e., research supporting climate change)*. The content will also be dictated *by either coming from a mostly conservative cite like Fox News or, a mostly liberal cite like CNN.* Articles will be matched as identically as possible with content, mood, and length as variables that will be kept in mind as articles are chosen. To reduce demand characteristics (e.g., the participants being aware the respondent is a bot) followers will be purchased, depending on cost, in accordance with the desired political affiliation. Once assigned to one of the six possible conditions a bot with the corresponding characteristics will tweet at the user with a simple message such as: “There is a lot of good information on what is happening – you should give the idea a chance!”  As this study will feature a within-subjects design as participants will have their climate change tweet scored longitudinally after the treatment, and compared to the score before the treatment where differences will be analyzed with the hypothesis that individuals will care most about the political affiliation of the bot, with all other effects paling in comparison. These conditions are established to most leverage differences in heterogeneity of treatment affects, and investigate which types of information individuals are most likely to digest and dismiss. 

##Advantages and Disadvantages:
Firstly, this study should yield very sound external validity. With a long enough period of time analyzed a robust data set should be very achievable and allow for generalizability. Furthermore, this design should replicate an organic way in which one might receive and consume information about climate change. Other studies which have similarily looked to map how participants receive information about climate change have not had the advantage of utilizing xonditions to parse apart heterogeneity of response – many of these large scale surveys from site like the Yale Program on Climate [Change]( http://climatecommunication.yale.edu/topic/beliefs-attitudes/) are certainly important, but are ultimately unable to reveal mechanisms or nuance in datasets. The isolation of these mechanisms and heterogeneous effects should allow for insight previously unavailable in the literature. This methodology also has advantages over other computational methodologies in that rather than relying on principles such as matching design (in the instance of natural experimentation) to ensure heterogeneity, the researchers can do so with thorough conditions.

However, there are also many disadvantages to this study and the application of experimentation to this topic. First and foremost, there might be a hydraulic tradeoff of external validity for internal validity here. For example, while the simply suggesting of news articles on social media is representative of how many may consume research on climate change - and tweeting a reasonable medium for voicing one’s opinions - the tweeting of negative remarks towards climate change may not be indicative of global disapproval towards climate change, it may be contextual disapproval. Furthermore, the proposed method in which we would scrape Twitter data could be very unreliable in finding tweets which match our search, and may instead just return tweets about people who support - or worse for the means of this study, challenge climate change. In addition to these issues, climate change may be much harder to harness as a day-to-day trending topic as compared to racism in the study done by Munger [(2017)]( https://link-springer-com.proxy.uchicago.edu/article/10.1007%2Fs11109-016-9373-5). 
What also may be of concern in this study are potential costs: monetary and ethical. While the Twitter data is public, there still exists potential for problems caused on the part of the participant as they have not consented to the study. Also, the cost of the bots could be potentially problematic without grant support.


Democrat Bot Condition |Republican Bot Condition
-----------------------|-------------------------
Democratic/Research/Fox|	Republican/Research/Fox
Democratic/Research/CNN|	Republican/Research/CNN
Democratic/Anecdote/CNN|	Republican/Anecdote/CNN
Democratic/Anecdote/Fox|	Republican/Anecdote/Fox
