---
title: 'Homework: Ethics'
author: "Kristopher Nichols"
date: "November 19, 2017"
output: 
markdown_document:
  theme: readable
---
**1. Assess this study using Salganik's four principles of ethical research.**

This study violated the principle of respect for persons by not respecting the participants' autonomy. The participants' autonomy was not completely respected due to the fact that researchers provided participants with potentially biased information (whether it be due to biased anchors or a conflict of interests on Adam Bonica's part), and framed this information as coming from the state of Montana, thus having more authority and being more objective. Having violated this autonomy, researchers further violated this principle by not allowing participants "additional protections" such as qualifying or contextual information on the nature of the study. Although this study did offer some information with the mailer - describing that it was a joint project between Stanford and Dartmouth, linked to a Stanford website for more information, and also included payment information - this was not adequate in this case. Hundreds of participants called in to complain about these mailers indicating that many participants felt mislead by this information, and if more information had been offered (while accepting that this would potentially allow for more obvious demand characteristics) this issue may have been avoided.
	
This study did not violate the principle of beneficence as much as they may have violated the other principles, but it could be argued that there was not enough consideration given to the weighing of costs and benefits. For example, researchers were not cognizant enough of the possibility for their biases of information and sampling could lead to an election outcome that was not representative of what the people of Montana may have wanted. Researchers did not give enough thought to the possibility of their efforts to make the mailers authentic confusing and misleading participants.
	
Concerning justice, the researchers may have violated this principle due to their error in sampling (referenced in question three). The study is potentially biased towards more left leaning individuals in that there was a vast discrepancy between the number of liberal and conservative individuals receiving the study, with tens of thousands more liberals receiving the mailer. Additionally, the mailer featured anchors as means for comparison, but the mailer unjustly used a current president to gauge liberalness and a politician who was recently beaten by said president as an anchor for conservativeness. Therefore, it could be said that these mailings did not give enough thought to the potential risks of the study (biasing election results towards more liberal politicians) for more conservative participants (i.e., the risks of the study were more harmful for conservative participants than liberal participants).
	
The study's violation of the principle of respect for law and public interest are more obvious than their violation of the other principles due to the findings of Jonathan Motl, Commissioner of Political Practices of the State of Montana. He found that researchers violated Montana's laws requiring "reporting and disclosure of independent expenditures." This is representative of researchers' breach of the compliance component. More specifically, researchers violated the component of transparency-based accountability by not being completely forthcoming concerning the study's general purpose and methods. The study did include a short description of the contributing universities and their funding, but said nothing of their more general goals, methods, and expected outcomes - information included in a typical consent document.
	
**2. Under what conditions might this mailing have altered the outcome of the Supreme Court Justice election?**

Random sampling may have allowed for greater external validity and more sound research ethics, but as detailed in the researcher's violation of the principle of beneficence, the potential risk of biasing the outcome would not necessarily be solved. The risk of biasing the election results are more connected to this study's portrayal of candidates on a scale from Mitt Romney as the conservative anchor and Barack Obama as the liberal anchor. This could potentially bias *all* participants, as participants may be more likely to vote for candidates who are presented as being more like the president, and winner of the (then) most recent election than those candidates compared to the loser of the same election. In this condition the study could alter the outcome of the election favorably towards those justice candidates that were more liberal and more like Barack Obama. 
	
**3. Discrepancies in mailer distribution**

The fact that researchers distributed far more mailers to liberal leaning voters in Democratic precincts potentially involves even more liberal bias in the study. Although the researchers validate their reasonings for doings so, this still seems very biased. This paints the  researcher as leaning heavily towards a desired outcome - getting liberals out to vote for the liberal candidates to win. Although I understand that this discrepancy was perhaps important in researchers' goals of proving that this information could affect voter turnout, this still seems too biased, and perhaps unethical.
	
**4. Choice of election**

Similar to the discrepancy between the number of conservative and liberal voters the mailers were dispersed to, although the intentions of this design choice are obvious, this was not respectful of Montanans and their justice. This design choice is understandable in the way that the researchers seemed to want to cause as little harm as possible by choosing an election that they deemed not likely to be swayed and thus more ethical to manipulate. However, this seems like an infraction of the principle of justice because as described by Dan Schnur, it seems deliberate that researchers chose Montana in a form of condescension.  It seems very unlikely that the researchers would have chosen any election in California and chose Montanans because they viewed them as more ethical to manipulate. 
	
**5. Results**

Although the results of the election were not particularly close, the methods the researchers used in the study were still unethical. Furthermore, I don't think it is terribly convincing that the results went as predicted, and therefore any potential risks are deemed as not having occurred. The candidate who won in each case was the candidate who was compared more favorably, and although the margins of victory were quite large, the study likely most affected the candidates who won in each case, further marginalizing the more conservative voters.

**6. Adam Bonica**

Adam Bonica's company CrowdPAC and the nature of its paid services does introduce worries about potential conflict of interests. Worst case scenario, Bonica was payed a large sum of money to attempt to influence the election in Montana, and he influenced the study to choose Montana, manipulating his research methods to do so. Although this is unlikely, this is still a potential concern, and one that should have been addressed by the researchers. It could also be the case that Bonica's company funded this project due to its vested interests in the topic of organizing activist communities and the implications this research's findings would have for this line of work. If this were true, this would also introduce more direct biases and implications. These lead me to believe that Bonica should not have been involved in the study as he introduced too many potential confounds and biases.
	
**7. Potential Changes**

To address the most glaring ethical issues with the study (the selection bias of Montana, lack of information on the study in the mailer, and sampling bias) I propose two changes in the research: that a more detailed informed consent be sent with all the mailers (without state logo), and that the researchers employ a natural experiment design. This design will demand a matching component that will force researchers to find comparable elections (matching across political leanings of the state, population, and size/importance of the election). A natural experiment design would allow for a multitude of benefits as it would help with the violation of justice in choosing Montana over some other state and allow for controlling for political affiliation of the state and election. This design would also help address beneficence as it would allow for proper spreading of risks. The benefit of the consent forms are more obvious. Although it would allow for potential reactance and demand characteristics, this would be a more ethically responsible design. It would provide participants with adequate information on the study and solve issues with the respect for persons principle. If I were interested in other variables influencing voter turnout I would adopt a similar natural experiment design and simply match across more variables. Also, potentially beneficial would be an Amazon Mechanical Turk study in which participants are given information for a certain geographically proximal region, and are prompted to complete a second part of the study after the election had ceased. Although this design would be open to simple lying, it would allow for a huge subject pool and more freedom for questions asked and 
