---
title: "Defending Celebrities: An Analysis of the Extended Self"
author: "Ling Dai"
date: 2017-10-30
output: 
    html_document:
       theme: readable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

####Research Problem Statement
The proposed research is aimed to investigate whether celebrities can be incorporated into the concept of extended Self by examining whether and when an individual who identifies with a celebrity will defend the celebrity when the image of that celebrity is threatened. Our theory is that, if an individual identifies closely with a celebrity, the celebrity might become a part of the individual¡¯s extended Self. In this case, we expect that a threat to the image of the celebrity will trigger the same response as a threat to the self. More specifically, we expect the individual to defend the celebrity by exhibiting a positive change in attitude towards the celebrity after receiving the threat. In our research, the threat will take the form of a post that contains a piece of negative information on the celebrity. In this research, besides how closely the individual identifies with the celebrity, we will also take into consideration some factors previously shown to influence people¡¯s defensive responses to personal and relational self-threats, such as implicit self-esteem and whether the self-concept is activated before the threat.

#### Background and Significance
In modern behavioral psychology, the self-concept is viewed as a dynamic knowledge structure, consisting of multiple self-relevant attributes, traits, and roles, organized into a multi-faceted and interconnected network that then filters and guides experience and behavior (Markus & Wurf, 1987; McConnell, 2011)  This view of the self is consistent with the original theorizing of William James, who laid the foundations for modern conceptions of self: "A man's Self is the sum total of all that he CAN call his, not only his body and his psychic powers, but his clothes and his house, his wife and children, his ancestors and friends, his reputation and works, his lands, and yacht and back-account. All these things give him the same emotions. If they wax and prosper, he feels triumphant; if they dwindle and die away, he feels cast down, -not necessarily in the same degree for each thing, but in much the same way for all." (William James, 1890)

Past researches have already proved that material objects that serves as a way of self-expression, as well as commercial brands that a person closely relates to, can be incorporated into the notion of the extended Self.(Lisjak, Lee and Gardner, 2012) Similarly, we theorize that if an individual closely identify with a celebrity, the celebrity may become a part of the individual¡¯s extended self. Understanding whether the concept of extended Self applies to the relationship between fans and celebrities not only helps us further complete the definition of the extended Self, but also facilitates the study on defensiveness and public relations.


#### Research Design and Proposal
1. **Hypothesis:**  
Our hypothesis is that, when the image of a celebrity is threatened, individuals who closely identify themselves with that celebrity will show significantly different responses as compared to other people. More specifically, a person who doesn¡¯t relate himself/herself with the celebrity will likely to have a more negative attitude towards the celebrity after reading the post. However, a person who identifies closely with the celebrity may defend the celebrity by showing a more positive attitude towards the celebrity even after reading a negative post on the celebrity. Therefore, we expect a statistically significant difference between the cross-group treatment effects (average changes in attitude after reading the posts).

2. **Experiment:**
   
    (a) *Participant recruitment and pre-experiment survey:*  
   The participants will be recruited online via the Amazon MTurk platform. For the purposes of screening and collecting basic background information of the participants, a survey will be filled out by each participant at the beginning of the experiment. During the survey, participants will be asked about some basic questions on their identities (age, gender, ethnicity, etc.) and to complete the explicit and implicit self-esteem measures. Explicit self-esteem will be measured using the Rosenberg Self-Esteem Scale (¦Á = 0.87) and Implicit self-esteem will be measured by asking how much the participants like their name on a 9-point scale ranging from 1 (not at all) to 9 (very much).
   
    (b) *Randomization and Delivery of Treatment:*  
   The proposed experiment uses three treatment groups. Because we mainly want to investigate whether people will defend against their extended self-concept, the participants in our main treatment group will be assigned to read a post that contains a piece of negative information about the celebrities they choose. However, to ensure that our experiment is working properly, we will also include another two treatments groups as our controls. Participants in the first control group will be assigned to read a post that contains a piece of neutral information about the celebrities they chose (e.g. the age of the celebrity). Our expectation is that all participants in this treatment group should exhibit no change in their attitudes toward the celebrity after reading the post. People in the other control group will read a post that contains a piece of positive information on the celebrities they choose. We expect all participants in this group to exhibit a positive shift in their attitudes toward the celebrities after reading the post.   
   The treatments are delivered to the participants usign a randomized design. For each celebrity, a participant will be randomly assigned to read a positive/neutral/negative post after answering the two questions. In the first quesiton, the participants are asked to report their attitude toward the celebrity on a 17 point scale: "On a scale of -8 to 8, please rate your attitude toward the celebrity (-8 = negative, unfavorable, dislike very much; 8 = positive, favorable, like very much; ¦Á = 0.98)." The second question is a replication of the Self-Brand Connection Scale (Escalas & Bettman, 2003): "On a scale of 1 to 9, how do you agree with the following statement? I identify with the celebrity (1 = strongly disagree, 9 = strongly agree, ¦Á = 0.95)"
   
    (c) *Measurement of outcomes:*  
   Immediatley after reading each post, the participants will be asked to report their attitude toward the celebrity again: "On a scale of -8 to 8, please rate your attitude toward the celebrity (-8 = negative, unfavorable, dislike very much; 8 = positive, favorable, like very much; ¦Á = .98)" And the change in attitude will be calculated from the difference between the pre-treatment and post-treatment survey answers. After that, we will perform a linear regression to explain the correlation between the how strongly individual identifies with the celebrities and their responses to the threates (changes in attitude). The implicit self-esteem of the participants will also be included in the model, as past researches have shown that self-esteem also plays an important role in determining people's defensive responses.
       
#### Assessment of the Experimental Design
*Experimental validity:*  
The proposed experiment has an improved internal validity as compared to traditional experiments. Whereas traditional experiments are usually subject to human errors in lab settings, by conducting the experiment online, we can eliminate the possibility of human errors on carrying out the experiments. However, conducting the research online also has certain disadvantages. For example, because the experiment is carried out remotely, it will be harder not only to provide guidance to the participants, but also to ensure their level of attentiveness during the experiment. To make up for these disadvantages, we need to make the survey questions more straightforward, and to make the structure of the experiment easy to follow. Moreover, we can check the attentiveness of our participants by adding attention checks into the experiment.

One weakness of our experiment is its external validity. Because only a very limited number of celebrities are involved in this experiment, it will be relatively hard to generalize the outcome and apply it to all celebrities. In fact, the definition of celebrity itself is also very loosely defined. In an attempt to address the potential lack of external validity in this experiment, we will select celebrities from different areas, such as politics, business and music. This measure should theoretically increase the generalizability of our experimental outcomes. Another source of lack of external validity comes from our sample of participants. Even though conducting the research via Amazon MTurk should theoretically eliminate a lot of geographical selection bias, the fact that most of our participants are from the United States severely limits our ability to generalize our experimental outcomes to people in other countries, especially those with vastly different cultures from the United States such as China and Japan.

*Heterogeneity of treatment effects:*  
Compared to traditional experiments, the proposed experiment also offers an enhanced ability to measure the heterogeneity of treatment effects by recording more background information of the participants.  For example, past researches on self-identification revealed that people with different levels of implicit self-esteem will likely to exhibit different responses. More specifically, participants with low implicit self-esteem are more likely to defend their extended selves, as compared to their high implicit self-esteem counterparts. Other characteristics of the participants that may also play a role in determining the treatment effects of the participants, such as age, gender, ethnicity, and profession, are also recorded in the pre-experiment survey to increase our ability to measure the heterogeneity of treatment effects.

#### References Cited
1. Markus, H., & Wurf, E. (1987). The dynamic self-concept: A social psychological perspective. Annual Review of Psychology, 38, 299-337.
2. McConnell, A. R. (2011). The multiple self-aspects framework:Self-concept representation and its implications. Personality and Social Psychology Review, 15, 3-27.
3. Lisjak, M., Lee, A. Y., & Gardner, W. (2012). when a threat to the brand is a threat to the Self: the importance of brand identification and implicit self-esteem in predicting Defensiveness.SAGE Publications.
4. Escalas, J. E., & Bettman, J. R. (2003). You are what they eat: The influence of reference groups on consumers¡¯ connections to brands. Journal of Consumer Psychology, 13, 339-348.
