---
title: "The ethics of the Montana election experiment"
author: "Ling Dai"
date: "11/20/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The Montana election experiment conducted by researchers from Stanford and Dartmouth in 2014 generated complaints from Montana voters and were criticized for its potentially problematic research ethics. In this essay, I am going to assess the ethics of the Montana election experiment using the framework of Salganik¡¯s four principles of ethical research: Respect for persons, Beneficence, Justice and Respect for law and public interest.
 
First, the principle of Respect for Persons suggests that researchers should try to acquire consent from the participants in most cases. In the case of the Montana election experiment, the researchers violated this principle by not seeking consent from the voters, the election candidates, and the government of Montana. First of all, although the researchers claimed the mailer to be relatively objective, the mailers might still have the potential to alter voters¡¯ view on the candidates, thereby changing the outcome of the election. Therefore, the researchers had the responsibility to ask for consent from the voters and the candidates. Moreover, including a reproduction of The Great Seal of the State of Montana in the mailer without the consent of the government of Montana is not only a violation of the principle of Respect for Person, but also a violation of the State Law.
 
The principle of Beneficence is about understanding and improving the risk/benefit profile of the research, and then deciding if the experiment strikes the right balance. Personally, I believe the researchers did not do a good job to minimize the potential risks of the Montana election experiment. First of all, the potential benefit for voters who received the mailers was to vote for the candidates that were in better alignment to their political standpoints. The risks for the voters, however, was to be misled by the information provided by the mailer, thereby voting for persons that did not represent their real interests. For the candidates, the major potential benefit/risk is to receive more/less votes, respectively, due to the influence of the experiment. And for the Montana State government, the potential risks are (1) altered election outcome; and (2) people associating the mailers with the government. From my point of view, many of these potential risks can be reduced simply by changing the information provided to the voters. For example, instead of providing information on where the candidates lie on the conservative-liberal spectrum, the researchers could offer more objective information of the candidates, such as their age, past experiences, etc. Moreover, the researchers could also include helpful information such as where and when to vote, which could provide convenience to the voters.
 
Third, Justice in academic researches is about ensuring that the risks and benefits of research are distributed fairly. According to a letter sent out by the researchers, the mailer ¡°was not affiliated with any political party, candidate or organization, and was not intended to influence any race.¡± However, we should look into the details of the experiment itself to decide whether the research fits the requirement of Justice. Among all, I personally view the selection of voters is the most deciding factor: if the sampling method was used, the experiment could have a potential to tilt the election outcomes, thus violating the Principle of Justice. In fact, even random sampling can compromise the objectivity of the research under certain conditions, which I will discuss in details later.
 
Respect for Law and Public Interest extends the principle of Beneficence beyond specific research participants in include all relevant stakeholders, and it has two distinct components: (1) Compliance and (2) Transparency-based accountability. From my point of view, the Montana election experiment violated this principle not only because it did not obey local laws and regulations, but also because the experiment had very poor transparency. As a matter of fact, the researchers from Stanford and Dartmouth were accused of violating Montana campaign practice laws which required registration, reporting and disclosure of independent expenditures. Moreover, the researchers did not make public any information on their research until they received a formal complaint from the voters and the Montana state government. Instead of making clarifications after the PR crisis happened, the researchers should release information about the research plan before the research even started.
 
Assuming that the mailers were sent to a random sample of voters, the research could still have altered the election outcome in cases where the treatment effect (of reading the mailers) varies across different groups of voters. For example, if the mailer makes liberal voters much more likely to vote while not having a significance influence on conservative voters, the experiment may tilt the election outcome in favor of the candidates who are identified as more liberal.
 
According to a report by Jeremy Johnson (a political scientist who assisted in the investigation), the mailers were not sent out to a random sample of voters. Instead, the mailers "were sent to 64,265 voters identified as likely liberal to centrist leaning in Democratic leaning precincts and 39,515 voters identified as conservative to centrist in Republican leaning precincts¡±. Although the researchers responded by claiming that because they anticipated the turnout rate to be much lower among Democratic voters as compared to Republican voters, the disparity between Democratic and Republican numbers should in fact help maintain the original election outcome, I still find their approach somewhat troubling.
 
The fact that the researchers picked this specific election in part because neither judicial race had been closely contested itself does make the experiment more ethical in its design. By doing necessary due diligence and analyzing the election results based on historical trends, the researchers at least attempted to make sure that the election results were unlikely to be altered by the experiment. This step is crucial from both the aspect of Beneficence and the aspect of Justice. First of all, analyzing the likely outcome of the election helped reduce some risks associated with the experiment. Hadn¡¯t the researchers conduct analysis prior to their experiment, there would be a chance that they instead chose an election in which the outcomes are likely to be changed. Second, by minimizing the chance of altering the election outcomes, the researchers ensured that no political parties/groups would benefit from the experiment itself and that the risk/benefit distribution was not disturbed.
 
In alignment with the prediction of the researchers, the election result turned out to be not particularly close: Jim Rice, the winner for Supreme Court Justice #1 received 78.22% of the total votes, and Mike Wheat, the winner for Supreme Court Justice #2, received 59.06% of the total votes. Although the result of the election further ensured us that the election results were unlikely to be altered by the experiment, and the claim that the researchers conducted analysis on the election result prior to the experiment, it does not significantly change my assessment of the research itself, because our assessment should be based on the designs and approaches the experiment adopted, instead of merely on the results. For example, even if the election results are not changed by an experiment with problematic research ethics, future experiments with similar flaws in their experimental designs or ethics lead to even greater harms than an intervened election.
 
For me, the fact that one of the major investigator for the Montana election study (Adam Bonica) is also the co-founder of CrowdPAC raises more concerns on the ethics of the experiment, because the business interests of this investigator might compromised the experimental design. As I have mentioned, for the mere purpose of investigating whether voters are more likely to vote when they are given more information, it wasn¡¯t really necessary to put the ¡°political positions¡± of election candidates onto the mailers. However, the is a possibility that the researchers decided to use this type of information partly because it fitted the business interests of Adam Bonica. And if that is the case, because the risks associated with the academic research was not properly assessed and minimized due to monetary interests, the ethics of the experiment should be more rigorously judged and relevant researchers should be held responsible for the potential damage caused by the experiment.
 
If I am the principle investigator interested in exploring whether additional information increases voter turnout in nonpartisan races, I would have designed the experiment differently mainly from two aspects: (1) having consent from the Montana State government and a group of voters before the experiment; and (2) providing voters with more objective information as compared to the ¡°political positions¡± of the candidates. First of all, even with proper experimental design and risk-minimizing measures, there is still a slight possibility that the experiment can tilt the election outcomes. Therefore, it is crucial to inform the government prior to the experiment and seek for their consent. Moreover, although seeking consent from every single participant in the experiment seems unnecessarily costly, it is also helpful to acquire consent from a group of randomly selected participants, not only because it fits the principle of Respect for Persons, but also because the participants may provide constructive feedbacks. More importantly, instead of using the ¡°political positions¡± of the candidates generated by CrowdPAC, I will provide the voters with more objective information that are publicly available, such as the working experiences of the candidates in the past.
