---
title: 'Homework 1: Proposing an Observational Study'
output: html_document
---

I) Introduction

Oklahoma has consistently ranked as one of the lowest achieving states when it comes to education. However, that is not to say there have not been concerted efforts to improve the accessibility and quality of the education for children in the state. One of the primary issues is how well the schools are funded. It is popular to assert that having, and by extension spending, more money will naturally increase performance. However, despite Oklahoma spending nearly 40% of its annual state budget on education efforts, school districts have shown minimal achievement when it comes to student test scores. 

In Oklahoma, a majority of the communities are agrarian with low population densities. Rural areas face challenges much different than rural areas, but they both have disproportionately high number of impoverished students. As such, state fiscal policy grants these rural communities additional revenue through the motor vehicle tax and the gross production tax. It has been the subject of much debate whether these additional revenues give these rural districts an unfair advantage over the more densely populated suburban and urban districts. The debate has become even more relevant in recent years since the gross production tax takes a percentage of the oil and fracking production, which takes place almost exclusively in rural areas of Oklahoma, has given some school districts a windfall of revenue.

The students of Oklahoma are evaluated in core subjects each year. The results of the evaluations are used to grade the schools on an A – F system. The A – F framework evaluates based on several criteria, but is generally accepted as the standard for assessing the success of a school. Given the attitude that increased spending naturally will lead to higher test scores and student achievement, we can observe the reality of this notion. My observational study will focus on the relationship between these additional taxes that rural communities get and the rural school districts scores on the state’s A-F Report card. 

II) Research Question:

The motor vehicle tax and the gross production tax are designed to increase the amount of revenue that rural (i.e. independent) school districts in Oklahoma receive. By extension, the increased revenue increases the district’s “buying power” for resources which should ultimately improve the student outcomes seen in the OKSDE A – F Report Card for schools. 

Do increases in school revenues, effectively increasing a school district’s “buying power”, result an increase in student achievement and performance on the Oklahoma State Department of Education A – F School Report Card from the previous year?


III) Research Execution:

The Oklahoma State Department of Education has shown a significant commitment to governmental transparency. Proof of this is the rich data sources that they have published on their website for public access (here). More importantly, it has provided detailed revenue and expenditure data for each school district in Oklahoma from the Oklahoma Cost Accounting System (OCAS). These detail records include the revenue amount, object and fund code for revenues, and the expenditure for each fund, function and object code. These detailed records allow for the ability to sort, and extract detailed information related to the specific tax revenues for the motor vehicle and gross production tax as well as the ability to see how a school district is spending the money. Because this observational study aims to explore if there is a causal relationship between expenditure and performance, it will require other factors such as teacher records, previous A-F performance metrics and student demographic and attendance data. All of which can be found within the OKSDE’s Public Records page.  

While the data is readily available, it can be difficult to easily associate the files. Fortunately, a MySQL database has been built to circumvent the encumbrance of maintaining and preprocessing data files. The MySQL data base was created, deployed and is currently maintained by the technology department at the Oklahoma Public School Resource Center (OSPRC). OPSRC is a non-profit in Oklahoma City that works with public schools to improve the availability and accessibility of quality education throughout the state. The database contains all information included on the previously mentioned public records page, as well as information acquired through Freedom of Information Act Request. 

Using the OPSRC database which contains the detailed financial records of school district expenditures and revenues, we will run queries that identify school Districts as either Independent or Dependent districts, these can be distinguished based on the District Key value the state provides, it acts as a district type flag. Then using the aggregate function in MySQL, aggregate the total revenue that independent school districts receive, specifically the motor vehicle tax and the gross production tax. This information can be aggregated for each independent school district for the past several years. Then using, the additional data collected and maintained by the OPSRC database, I will associate the A-F School Letter Grade parameters with the school district for the given year. For example, the A-F evaluates the bottom quartile student growth, the share of students that test proficient and advance by subject and more. Other data that I will include in the aggregate file includes the Average Daily Attendance (ADA), Average Daily Membership (ADM), number of certified staff, number of teacher by grade, number of teacher by subject, and total revenue. I will then aggregate the same information, minus the total motor vehicle taxes and total gross production taxes, for the dependent schools. 

In ‘Bit by Bit’, Salganik defines the “matching” method as ‘the research looks through non-experimental data to create pairs of people that similar except that one has received the treatment and one has not”. Similar to the Einav and colleagues experiment that Salganik outlines, we are interested in comparing a treatment effect, and as such require that we use fair comparisons between our treatment and control groups. Here, the treatment group is the independent (rural) school districts receiving the motor vehicle and gross production tax, while the control group are the dependent districts not receiving those tax revenues. 

Our detailed and historic data set allows us to control for the various other factors that influence school’s performance, and it is why it was included in the initial aggregation of data. Because things like ADA, ADM, and student teacher ratio (i.e. classroom size) have all been explored extensively in academia, and are available in the data set, we will control for those factors impact on the performance of the A-F report card. In this observational study, we will focus on controlling for student teacher ratio, percent of students that receive special education services and percent of students that qualify for Free and Reduced Lunch. These three factors have historically proven to be major factors in a school and school district’s performance.

By creating what Salganik refers to as ‘matched sets’, based on the properties outlined in the previous paragraphs, we can identify subtleties that a lump average of the two groups glazes over. One way to assess the impact of the motor vehicle tax and the gross production taxes is to show the distribution of the index scores (i.e. the overall grade the district receives, similar to how typical A – F grades work in classrooms) between the treatment and control groups. To further explore this relationship, distributions can be shown for stratified matching pairs for things like ADM, ADA, and student-teacher ratio. Similar to figure 2.8 in Salganik’s chapter on Matching (2.4.3.2) comparing the effect of start price on sale and the effect of start price on sale price, we could use this approach to help characterize different strata, groups of schools, or matched pairs. Ideally, the categorization of sale items on eBay in Einov and colleague’s paper can act as an analog to characteristics of different schools in Oklahoma to measure the impact of revenue and performance. 

A natural extension of this project is as a predictive model. Using tools like linear regression and other predictive techniques, we can identify characteristics of schools that will help build more effective models for predicting the outcomes of school districts on the A – F Report card

IV) Relationship to 'Big Data':

This observational approach is beneficial in several ways and leverages the advantages of big data. First, the data is non-reactive in that the records or the literal observations will not change once it has become subject to analysis. Since the data is public record and subject to several transparency statutes and laws, it must contain detailed information and is specifically designed to be as transparent as possible. It is extremely difficult to manipulate the data in a way that will obfuscate the truth.  Furthermore, since we are comparing historical data, the records cannot be changed post-hoc, meaning that once a school district has received a letter grade, it cannot be otherwise changed. Having this data set allows for objective analysis and exploration.

Second, the data for this study if “big”, while not as big as collecting user data off of social media, it is large for the education sector. The revenue and expenditure data is comprised of over a million lines of unique, detailed data, collected over several years, making it extremely useful in detecting subtle changes in either revenues or expenditures over an extended period of time. Furthermore, the data reflects all school districts in the state. In most cases, capturing an entire population is extremely difficult, but in the case of this observational study, we are able to capture all 570 plus school districts in accurate and detailed record to examine and observe. 

While there are certainly benefits, this observational study does have several drawbacks. The primary drawback is the sensitivity of the data. Schools and teachers are constantly under scrutiny and are facing increasingly difficult work place environment. Publishing the results that single out communities or schools could result in political or social back lash since the data set is finite enough to reverse engineer and identify the exact school districts in question. 

School and education data is also notorious for being incomplete. While the revenues and expenditures data is extremely detailed, the ADM, ADA, demographics and student-teacher ratio records can often be subject to human error or due to the lack of technology that can accurately capture these important conditions. Furthermore, due to privacy issues, important fields like test results are often redacted under federal privacy laws that protect students (FERPA). Because we are working with a finite set of school districts, missing data becomes an increasingly important issue because it may bias the results of the observations. 



