---
output: github_document
---
# Ethics of the Montana Election Experiment
By: Bethany Bailey

In the Montana Election Experiment, researchers sent out mailers to 102,780 Montana voters in order to determine whether voters are more likely to turn out to vote when given more information. Though an important research question, there were many problems with this research. This study included deception, unequal distribution of treatment, partisan labeling, and lack of transparency. Further, the researchers did not create a sound experimental design and minimize potential harm. Thus, there are many ways these researchers could have better utilized the methods of ethical research in this study, which I outline below.

## Four Principles of Ethical Research

### i. Respect for Persons
The first principal of ethical research is respect for persons, which states that individuals should be treated as autonomous and, when possible, be able to decide whether or not to participate in a study. Even though one could argue that the treatment in this study (receiving a mailer on the "partisanship" of potential justices) was minimally harmful or harmless, the researchers did not make an effort to get informed consent from participants. This violates the first principle. However, given the quantity of individuals in this study (102,780), this informed consent would have been near impossible to receive. Additionally, getting informed consent could cloud the results of the study, because if the participants were aware of the research, it might change their likelihood of voting. I believe that in the absence of informed consent, the researchers should have provided a means for the participants to learn more about the study. They could have done this through a clearer description at the bottom of the mailer or a link to a website with more information about their research (rather than just their data).

The second part of respect for persons is that individuals with diminished autonomy should be entitled to additional protections. This study did not specifically target any disadvantaged populations, and because it was a voter study, it was only conducted on people over the age of 18. Thus, I do not think the researchers violated this principle.

### ii. Beneficence
The principle of beneficence argues that researchers should do no harm, and they should try to maximize potential benefits and minimize potential harm. This research followed the "do no harm" rule in that it tried to make clear that the information they were sharing was non-partisan. Further, they attempted to minimize potential influence on the election by doing the experiment in what was thought to be a non-contested election.

However, I do not believe this study strikes the right balance. Though the potential harms to individuals were minimal, the researchers could have done more to minimize them. For example, they could have minimized deception by not including the state seal. They could have made it clearer that the information was not provided by a government-sponsored agency. Instead of labeling their mailer, "2014 Montana General Election Voter Information Guide," they could have labeled it "Stanford/Dartmouth's Classification of Justices," or something else that made it clear that it was not endorsed by the state of Montana. They could have shown an attempt to weigh the positives and negatives by seeking approval from their IRB. They also could have used a smaller pool of participants. The researchers could have asked the same research question while minimizing the number of people potentially harmed in the research process.

### iii. Justice
The justice criterion states that researchers should attempt to distribute the burdens and benefits of research across the population. The results of this research were just in that they could have been utilized equally by both parties. Thus, the outcome could have been nonpartisan if the researchers had clearly distributed information about their results across the population. However, it was unjust for three main reasons: (1) their skewed sample population, (2) lack of compensation, and (3) potential harm to justices and the political system.

The main justice issue I see in this study is the sampling population. The researchers sent mailers to 64,265 liberal-centrist individuals and 39,515 conservative-centrist individuals. If the researchers' hypothesis was correct and this increased voter turnout, it could influence democratic turnout more than conservative turnout and influence the election (even in an uncontested election). Similarly, if this information actually made people less likely to vote or harmed the participants, it would have harmed liberals twice as much as conservatives. To prevent this and create a more just study, the researchers could have provided information to equal numbers of Democrats and Republicans. They also should have distributed the burdens more evenly among states by conducting this study in multiple states, which would have the added benefit of increasing external validity. 

Secondly, individuals were not compensated for their participation in this study. I do not believe this is a major issue with this study for two main reasons: (1) the pool of participants was so large and remote that paying individuals was not feasible, and (2) the participants were not asked to do anything particularly invasive or change their lives in any way, so pay was not necessary. 

Thirdly, labeling judges on partisan lines in a non-partisan election could potentially decrease or increase the likelihood of the population to vote for them. If the population leaned more democratic or republican, this would help some judges more than others. Thus, the burdens and benefits of the research would not have been equally distributed among the judges and the political parties.

### iv. Respect for Law and Public Interest
The last principle, respect for law, states that researchers should attempt to comply with all applicable laws, terms of service, and contracts. The researchers in this study showed no real effort to identify and obey relevant laws/contracts. For example, using the Great Seal of the State of Montana in an attempt to make the mailer look official was likely a violation of Montana state law. Further, though their study could have assisted certain judges’ elections in the ways outlined above, they did not register or report their research expenditures to the state. Thus, the Commissioner of Political Practices of the State of Montana determined that this research violated Montana state law.

The second aspect of this principle is transparency-based accountability: researchers should be clear about the goals, methods, and results of their research and take responsibility for their actions. Though the researchers showed a minimal attempt to do this by adding information at the bottom of their mailer and providing a website with details about the data, they could have done much better. Here is the statement from the bottom of the mailer:

"For more information on how these figures were created, please see http://data.stanford.edu/dime. Please note that this guide is non-partisan and does not endorse any candidate or party. This guide was created as part of a joint research project at Stanford and Dartmouth."

The statement also said it was paid for by the researchers at Stanford and Dartmouth. However, the researchers could have made this statement clearer by stating that the mailer itself was part of a research project. They could have provided a method (perhaps a website) for individuals to visit if they were interested in the goals and methods of the research, or if the individuals wanted to opt-out of the study. They could have formatted the mailer in such a way that these statements were more evident to recipients.

Additionally, researchers should consider the public interest when designing their studies. This research could potentially benefit the public by providing information on what drives individuals to vote, and by increasing voter turnout. However, this could be harmful if the research results were not shared with the entire research and political community. Further, this research could do potential harm to the public interest by reducing justices to simple partisan ideology and politicizing nonpartisan judicial races. All in all, I do not think this research as conducted strikes a good balance of potential benefit to individuals and the public interest and respect for law, persons, and justice. 

## Random Sample: Alter the Outcome?
If the mailers had been sent to a random sample of voters, this mailing still could have altered the outcome of the Supreme Court Justice election. For example, perhaps liberals and conservatives are unequally likely to vote in response to election information. If this was true, one party might have responded to the information more than another, skewing the election results. By using previous politicians Barack Obama and Mitt Romney as comparison, the researchers might have skewed the results in favor of the judges closer in political leaning to the politician with the higher approval rating. Further, this could have influenced the election if the researchers were incorrect in their classification of partisanship and this affected people's perceptions of the justices.

## Non-Random Sampling and Research Design
The non-random sampling (sampling 25,000 more Democrats than Republicans) lessens my opinion of the research design, because it made it more likely that the researchers might influence the election and it did not spread the potential harm and benefit. Their justification - that they anticipated lower turnout from Democratic voters - does little to alleviate my concern. As previously mentioned, if this treatment caused a greater turnout among those who received the mailer, this could have influenced the results of the election. Further, this non-random sampling is just bad research design: it would be difficult to compare results among the groups if the research was not conducted on equal groups of the population.

## Assessing Influence: Contested Election?
By choosing a race that was not closely contested in the primary, the researchers demonstrated an attempt to do no harm. They thought that their research would not affect the outcome of the election, and this is a positive aspect of their study. However, it does not account for longer-term effects that thinking about judges in a partisan light and voting in the election might have on individuals and the public. It also does not explain why their sample was biased. Thus, this aspect of their study does not alleviate all of my concerns and make me think their study was ethical.

## Never a Close Race
Though the election turned out to have clear winners, (with 78% and 60% of people voting for the more "Democratic"" candidates), this does not clear the researchers of responsibility or change my assessment of the research. A consequentialist might argue that this research was justified because the end goal - gaining knowledge about what motivates people to vote - far outweighed the potential harm that could have been done, and further, that harm was not done because the race was not close. However, the research could have had unforeseen effects on individuals and the politicization of the justice system. Further, the difference between the second Justice seat was only 60,399 votes, which was smaller than their sample population. Thus, though they attempted to do no harm by not influencing this particular election, they did not do enough to weigh the other effects the research could have had.

## CrowdPAC
Adam Bonica's founding of and involvement with CrowdPAC does not change my assessment of the research. Though his use of the data that scored judicial candidates in this study might blur the lines between academic research and profit, it does not seem like Bonica used the information specifically collected in this study for his company. If he had used the resources of the university for this research and later used the results to assist partisan causes, I would find the ethics more nebulous. However, because it appears he is equally willing to take on diverse clients at his organization, and it is separate from his research, it does not cause me to judge the research more harshly or favorably.

## Suggestions for Improvements
If I were one of the principal investigators, I would use a similar format for this study (sending mailers to individuals in a supposedly non-contested election), with five important changes. These changes would make the study more ethically sound while still asking the same question: does increased information strengthen voter turnout in nonpartisan races?

1. I would not fake the state seal or try to deceive individuals. Research can study the effect of providing more information to voters while making it clear to individuals that they are participating in a research experiment. If I were conducting this study, I would make it clear that Montana citizens were receiving information from researchers, not state-sanctioned information. This would also prevent many of the potential legal issues with this research.

2. I would give more detailed, non-partisan information about the candidates on the mailer. Rather than providing individuals with any information on the judges’ ideas or previous rulings, this study boiled down a non-partisan election to partisan leanings and comparisons to well-known politicians. This was potentially damaging to the integrity of the political system and to individuals' understanding of their judges. Thus, if I were to do this study, I would not give people simple information on the "partisanship" of judges and compare them to well-known politicians. Instead, I would share some information about their previous rulings, campaign donations, or their demonstrated stances on specific issues. 

3. I would provide a method for individuals to learn more about the research and opt-out. On the mailer, I would provide a link that clearly identifies this project as research, outlines what it is trying to achieve, and allows individuals to opt-out if they do not want to participate. If a large or skewed portion of the population chose to do this, it might change the results of the study. However, this is an important component of ethical research. Further, I could use statistical methods to determine whether the results were likely skewed depending on the size and portion of the population that opted out.

4. I would apply treatment to a smaller and distributed population. I would provide information equally across the population of different races, genders, ages, and party affiliations. I would also lower the number of participants in the study. If the treatment effect was high enough, I would still be able to see results from a smaller population, without potentially influencing the election or harming individuals. 

5. I would submit my proposal to my Institutional Review Board. Per the letter from Dartmouth and Stanford following public outrage, this study was not submitted for IRB approval. By submitting to IRB, I would better ensure my research was following the most state-of-the-art ethical guidelines and any recent legal developments. This is an essential component of any social science research.

## Conclusion
Thinking through the potential wide-ranging consequences of research is necessary for any good experiment. Though I understand the hypothesis of this study and appreciate the knowledge the researchers were attempting to gain, I believe there were major ethical and experimental flaws. Thus, if I were to conduct similar research in the future, I would change many aspects of the study.
