# Proposing an Observational Study
### By: Bethany Bailey

## Research Question
A sudden market event, such as an unexpected negative earnings report for a security, often causes prices to drastically decline and then rally to more technically or fundamentally justifiable levels. This phenomenon is known as the oversold bounce (in the remainder of this paper, I will refer to these events as "bounces"). This response might be partially explained through behavioral tendencies such as herding, panic, and loss aversion. In this study, I propose using Bloomberg Terminal chat data (Instant Bloomberg, or IB) to analyze user behavior, specifically how communications between IB users change following major news events that cause bounces. Using these data, I will analyze the frequency, duration, and tone of communications in order to show a relationship between market activity and communications. 

### *Research Design*
This study involves counting and categorizing communications between IB users prior to, during, and following bounces. The population of interest is IB users in the respective markets affected by these events. This study has many aspects of a natural experiment - for example, it would track responses to events that appear random and are difficult to predict - however, I do not categorize it as a natural experiment because a random sample of people are not responding to market bounces.

### *Data Plan*
These data would be collected through a cooperation with Bloomberg L.P. Due to the sensitive and proprietary nature of these data, I foresee issues in collection, which I address in the "Feasibility" section. 
Bloomberg is required to keep logs of all chats on its service for compliance and regulatory disclosure. The data will draw from these logs, and will consist of anonymized chats, including content, time stamps, and if possible, a unique id for each user and their specific role in finance (the industry and their position, e.g. trader, operations, portfolio manager, executive, etc.). This study is primarily descriptive. I plan to count the number of communications, the time between communications, and the tone of communications after the release of major market news in order to determine the contours of the relationship between communications and market behavior. Additionally, if successful in gaining access to anonymized unique identifiers of users, I will ask additional questions of the data, including whether the same groups of people communicate during overselling and the rally.

## "Good" Characteristics
Below, I outline the advantages of these data (outlined more generally in *Bit by Bit: Social Research in the Digital Age* by Matthew Salganik).

### *Big*
These data are valuable because they are substantial and consist of multiple different types of information. With approximately 325,000 terminal users (Bloomberg L.P) discussing market news, trades, and current events, the amount of data is vast. These data are big because they consist of:
  
  * a large amount of information 
  * generated by many observations
  * created by many people 
  * covering a large time scale
  
The data's size and complexity enables the study of rare events, such as the specific behavior of a bounce. If only a few thousand users utilized the terminal, this would not be possible because there would be insufficient information to make meaningful comparisons. Across this large dataset, small differences in the way traders think and communicate during bounces may be made legible, such as the inflection point where sentiment changes. The size would allow researchers to remove portions of the information without removing all relevant detail, allowing us to find significant differences in communication despite its sensitive nature. 

### *Always-On*
Another strength of these data is that they are always-on, allowing a researcher to go *back in time* to study these phenomena. This is essential, in that the reaction to market news is impossible to predict. The always-on nature of the data allows the study of bounces on different time scales and event levels, for example studying the time prior to, during, and following a bounce and comparing it to times of market stability. 

### *Non-Reactive*
These data are also non-reactive to researcher measurement. Though terminal users might modify their behavior because their data is being collected by compliance agents, this reactivity does not affect our study because it is the normal environment in which users perform. By collecting historical data, users would not be able to adjust behavior due to researcher involvement. This creates potential ethical and legal liabilities, as IB users assume their chats are not available to third parties. I hope to overcome this issue by anonymizing the data and only accessing information required by this study.

## Weaknesses, with Suggestions
Below, I outline the negative characteristics of these data, and how I would plan to minimize their effects.

### *Inaccessible/Sensitive*
Due to the sensitive and proprietary nature of these data, it would be difficult to gain access to demographics and company details. Much of the data of interest would be near impossible to access. However, due to the wealth of these data, research could be conducted after the dataset was de-identified. Working with Bloomberg, a researcher could identify portions of data that could be shared or analyzed without breaching user and regulatory agreements. Further, Bloomberg might have the capability and interest to conduct research like this with minimal researcher intrusion, which I further explain in the "Feasibility" section. 

### *Incomplete/Non-Representative*
These data are incomplete and potentially non-representative in a few ways:

  1. Because IB chat can be monitored by compliance and regulatory agencies, users might censor their communications. 
  2. IB is not used by all participants in the market (it is not the complete universe or a random sample).
  3. IB is not the only medium through which users communicate (it lacks phone calls, emails, face-to-face interaction).
  4. Some users create more activity than others.
  5. These data do not include other important information, such as price changes.
  
To overcome these biases, researchers could use anonymized user ids to analyze whether the data was biased toward certain users (4). Other important information could be found using additional databases (such as Bloomberg market data) (5). Also, there is a large enough concentration of IB users discussing market news and executing trades that missing data would have a negligible effect (2 and 3). Further, though users might adjust their behavior because they are tracked by compliance, this environment is inherent to finance, and thus would not change normal behavior (1).

### *Drift*
The volume and methodology of IB use has evolved with the markets, creating obstacles for a longitudinal study. For example, the IB user population might have changed as financial technology developed and traders in very liquid markets started to use automated systems to process data and make trades (population drift). This may also cause behavioral drift as users' needs, and thus use, change with the markets in which they work. I would overcome this obstacle by focusing on specific markets and short timescales. This drift, though potentially a weakness for research, might suggest potential for further study, such as how changes in user behavior relate to other market behavior.

### *Dirty*
These data have another issue: they include a lot of noise. Traders use this medium to discuss non-market related topics, for example, sports and new bars. Additionally, much like Back and colleagues' (2010) study of 9/11, these data have many identical entries because salespeople often copy-paste market information into multiple chats. However, by focusing on plain text communication during specific time frames following bounces and comparing the data to a baseline of plain text communication during times of little market change, I would aim to minimize this noise.

## Feasibility
The most obvious obstacle to this research is the sensitivity of these data. They are collected by a private company and legally unavailable in their original form. I would attempt to bypass this issue in a few ways.
 
  1. This research could be the outcome of a mutually beneficial partnership. Bloomberg is interested in maintaining its preeminence in the market. This study could help Bloomberg understand user behavior and demonstrate the essentiality of the Bloomberg terminal during market moves.
  2. Access to the entire data set is not necessary for this research. For the first part of the research (looking at the volume of chats and time between chats), no chat content would be necessary. This analysis would only require time stamps and unique user identifiers.
  3. Further research that measures sentiment or content could use a small sample of anonymized data. This could be sufficient to determine the categorization methodology. After this methodology was determined, research could be conducted at Bloomberg with algorithms created by researchers. Thus, sensitive information would not need to be released to researchers.
  
## Conclusion
This proposal outlines an observational study of financial chat data to determine a relationship between market activity and communications. Though the proposed data are not perfect, their strengths are evident and weaknesses can be counteracted. Similarly, though the proposed data are sensitive, their study has the potential for mutual benefit and minimal intrusion.
