# Proposing a Survey Study
### By: Bethany Bailey

## Research Question
USA Churches defines a megachurch as a church with an average weekly attendance [greater than 2,000 people](http://www.usachurches.org/church-sizes.htm). Understanding why young people attend these churches and how they engage with them socially is a question of interest to researchers and megachurch administrations alike. In this research, I would like to understand why certain young megachurch-goers participate in their church less actively than others. My main research question is as follows: What are the differences between active and passive participants among young US megachurch attendees? Do they have different experiences of their church, and are they seeking different outcomes from church?

## Population
The target population of this study are young members (18-29) of Protestant megachurches in the United States with over 10,000 attendees. The sample will only include churches with over 10,000 attendees because the size will enable us to more easily draw comparisons within the young subset of the population. This research is not necessarily generalizable to smaller megachurches. There are [approximately 90](http://hirr.hartsem.edu/cgi-bin/mega/db.pl?db=default&uid=default&view_records=1&ID=*&sb=3&so=descend) megachurches with over 10,000 attendees from which to sample. To attempt to minimize coverage error, data on each of the 90 churches' geographic location, denomination, racial makeup, and age of church will be collected. The researchers will choose ten churches (or a few more or less, depending on the overall population characteristics) that represent the target population of ninety churches most accurately based on these characteristics. The young people at these ten churches with constitute the frame population. 

To gain access, the researchers will contact each church administration, explain the scope of the study, and request their involvement. This research is mutually beneficial for the researchers and the church leaders; thus, access issues are not anticipated. However, if a church does not want to participate, another church with similar characteristics will be contacted in its stead. Though this could cause potential non-response bias, the number of churches and constituents interviewed should help alleviate some of this bias.

## Data Plan / Operationalized Question
Once the churches are chosen, pamphlets in the church bulletin will prompt young people (age 18-29) to download an app. Participants will also be asked to participate in the study by a church leader during Sunday services. Participants who download the app will be asked to complete an initial short survey of demographic information, including age, gender, marital status, how long they have attended the church, income, etc. This survey will later be used to weight the groups based on demographics in order to minimize sampling error. They will also be asked to consent to participate in the survey after reading through an explanation of the risks.

A person will be defined as an "active participant" if they (1) attend church 3 or more times a month and (2) if they participate in another church activity (a small group, volunteer activity, or mission trip). A person will be defined as a "passive participant" if they (1) attend church 3 or more times a month and (2) do not participate in any additional activities at the church. A non-participant is someone who attends church 2 or fewer times per month. The level of giving will not be used to define active/passive in this study, as the research is focused on the level of social involvement. The levels of participation will be determined first by asking the participants a series of questions at the beginning of the research about their church involvement. To minimize researcher bias, each participant will be able to add activities the researcher may have missed.

This study will be a combination of an Ecological Momentary Assessment (EMA) and wiki surveys. Participants will be asked questions before they go to church, during the sermon, right after church, and throughout the week. Most questions will take the form of a wiki survey. The question will randomly choose two responses from a pool of potential answers and provide the participants with the opportunity to contribute their own answer which will be added to the pool. For example, in order to glean information about the experience of these young churchgoers, the participant might be asked the following after church:

  * What did you enjoy more about your church experience today? 

and be given two randomly chosen answers from a pool of potential answers, along with the opportunity to contribute their own answer. For example, they may be prompted to answer:

  * Sense of community 
  * Pastor's sermon
  * Other: ________
  
Any additions will be reviewed by the researchers and added to the pool of potential answers. This will allow for easy data analysis while also allowing open responses, from which the researchers can gain information they otherwise lacked.

## Representation 
Though in theory everybody attending these churches between 18-29 has an equal probability of being chosen, non-response bias could be an issue in this study. This group will likely be unrepresentative of the sample population (especially because we are measuring participation levels). To counteract this, after noting any demographic differences between the active and passive groups, which may be interesting for future study, the research will compare the demographics of the respondents with those of the sample population using the church databases of attendees and weight responses based on this information. Most megachurches have records of their constituents, including a breakdown of attendees by age, gender, marital status, etc. 

## Measurement
As previously stated, this research aims to understand how young active and passive church participants differ in their experiences of and what they are seeking from church. The participants will be asked questions at various times throughout the week for a 3-month period. In order to minimize bias, questions will be asked at the same time (8pm) every day. Before, during, and after the church service, the participants will be asked questions about their experience.

A small sample of the potential questions are as follows:

  1. Activity questions
  
  * Did you participate in any church-related activity today? If so, what?
    - Small group
    - Volunteering
    - No activities
    - Other: ________
    
  The responses will be analyzed and self-reported responses will be added to survey for other participants. Most questions will take this wiki-survey format. This should help minimize question form effects within this research.
  
  If the churchgoer participated in a church event, questions about their experience (in the same wiki-survey format) will follow. For example, they might be asked:
  
  * What did you enjoy more about the activity?
    - Spiritual fulfillment
    - Spending time with fellow Christians
    - Other: ________
  
  2. Other questions during the week: What do they seek?
  
  During the week, participants will be asked other questions about what they seek in a church. These questions will also take the form of a wiki survey. For example:
  
  * What do you look for in a pastor?
    - Powerful
    - Eloquent
    - Other: ________
  
  3. Experiences of Church
  
  Before, during, and after the church service, the participants will be asked questions about their experience. 
  
  * On a scale of 1 to 5, how would you rate your church experience today?
  
  * What are you looking forward to more at church today? (Also a wiki survey)
    - Spiritual growth
    - Seeing my church community
    - Other: ________
  
In order to determine the potential answers, all of the above questions will be pretested with a sample of frame population. This sample will also be able to suggest their own questions. Hopefully, this will also minimize question form effects and other errors.

## Digitally Enhanced / Strengths of Method
This study is digitally enhanced in two main ways: (1) it contains survey questions in the form of a wiki survey and (2) it takes the overall form of an Ecological Momentary Assessment. These digitally-enhanced traits would strengthen the research. Collecting a large portion of the data using a wiki survey would allow us to gain more nuanced information about the groups' differences in what they look for in a church and how they experience church. It would allow us to learn more about people's lives and preferences while still making the data easy to process. Additionally, it might minimize non-response bias and inaccurate answers because participants would be asked only a few short questions at a time.

Using an Ecological Momentary Assessment would allow the researchers to ask questions at the relevant time and to track participants over time to see if their reported behavior matches their actual behavior. This is important because churchgoing is an area where social stigma might cause over reporting. Additionally, the general format of this study (an EMA survey) is better than a study using already-existing data because we are interested in the internal states of these participants, and their perceived experiences. The best way to glean that information is to ask them questions.
