---
title: "Reading apps, social network and reading habits in the digital era"
author: "Yilun Dai"
date: "10/22/2017"
output: html_document
---

  WeChat, China’s biggest social media, is now entering into the digital book market. Launched in 2015, its mobile reading app, WeReading, aims at providing high-quality, published e-books for WeChat users. WeReading’s user account is directly associated with the user’s WeChat account, enabling the user to post the books he or she is reading and to share his or her thoughts on these books. This idea of integrating social media and e-books is called “social-reading” by the developer, and the purpose of social-reading is to turn reading into an alternative way of social activities, and to increase the efficiency of reading during a digital era where browsing social media has taken up much of a person’s daily life. It seems that WeReading and its concepts of social reading not only increases users’ reading time in a digital era but also enhances their interactions with their friends on social media by letting them share their comments on the books they are reading. Past literatures on reading software and e-books have focused mainly the effectiveness of reading software in pedagogy, mostly using observational study methods. Few have studied the effectiveness of e-books among active social media users, or the impact of a social-reading app, using digitally enhanced survey methods. For instance, in Soft(a)ware in the English Classroom: Rekindling Reading: On the Use of E-readers in the English Classroom, Griswold and Lynch mentioned the “sharing” figure of kindle, which enables students to share their findings on twitter (102), but no surveys were conducted and no data from the students were collected. This study is going to use digitally-enhanced survey to address the question on the influence of social reading apps on users’ reading efficiency and reading habits and to measure the apps’ impact on users’ interactions with their friends on social media. \
    This research is going to quantify the impact of social reading apps using data from digitally-enhanced surveys. I will mainly use two digital platforms, WeReading, the social-reading app, and WeChat, China’s largest social media whose user accounts are directly associated with WeReading and where users of WeReading can share their thoughts, to distribute my surveys. The two platforms have different but associated features that are suitable for different needs and stages of this research. With WeReading, I can target the population that I would like to study. I will use the pop-up windows and banners in WeReading to distribute my surveys to the users. The books of WeReading are categorized, making it easier to target specific type of readers if necessary. Moreover, there is a “thoughts” module in WeReading, which can be helpful if we want to target readers who take notes while reading. With WeChat, as a social media with long sharing and interaction features, I can apply for an official account that collects data from the participants, and this official account has a built-in voting function that I can use to distribute closed questions. Furthermore, there is a “mini-program and games” figure in WeChat, allowing the design of interaction with the participants. The sampling method used in this research will be non-probability sampling as introduced by Salganik(2017), since the probability of inclusion is unknown for individuals in the population. \
    Four methods of asking questions introduced by Salganik (2017), Ecological momentary Assessment, Surveys linked other data, WeChat Vote (similar to Wiki Survey) and Gamification, will be included in this research. For conducting ecological momentary assessment, Pop-up windows will appear twice in a particular day, both before the participant begins reading on WeReading and after the participant finishes reading for that day. The first part of the survey, which takes place before the participant starts to read, will ask the participant the current time, his or her location (office, home, café, etc.), his or her age, whether he or she starts reading a new book or continues reading the old one, the types of book he or she is going to read, and if he or she intends to read in private mode (so that the books, the pages and the notes are not visible to other users). When the participant clicks on “exit” of the book page, the second half of the survey will pop out, prompting the participant to answer the time, the number of pages he or she has read, the number of notes (posts) he or she has taken, and the likelihood he or she is going to recommend the book to their friends. If participants choose to share the reading status and thoughts via WeChat, the survey will automatically keep track of this behavior, counting the number of times and participants who share their reading activities on the social media, creating a pool of data that link the times of sharing to other questions participants have answered and hence the other features of the participants. Collecting data of sharing and linking the data to the survey completed by the participants earlier corresponds to the Surveys linked to other method introduced by Salganik (2017). \
    WeChat Vote is a feature on WeChat that is similar to Wiki Surveys described by Salganik (2017). Establishing an official account will enable me to launch a vote on WeReading and its impact on reading habits. Since it is a vote, the questions are closed. However, participants are welcome to comment on the vote and leave any additional thoughts using the comment figure that is built within the WeChat Vote. The vote will include the frequency the participants use WeReading, the frequency of reading before and after using WeReading, the average time of surfing on social media before and after using WeReading, the main advantages, from their perspectives, of social reading apps over traditional paper-based reading (easy to carry, cost-saving, usage of fragmented time, easy note-taking, exchanging ideas with others). \
    Another method mentioned by Salganik(2017) will be gamification. I will use WeChat’s “miniprogram and games” feature to design a trivia based on the books the participant has recently read on WeReading. This trivia will prompt the participant to answer multiple choice questions on the contents of the books, and they can share their scores or invite their friends to participate in the trivia. Scores of the trivia will be used as a quantifiable measurement of the efficiency of reading on the social reading app.\ 
    The advantage of using survey rather than observational data is that this research studies people’s behavior. We will have limited knowledge of reading habits by using pure observational methods, because people’s comprehension of the books, their thoughts on the books themselves, and their opinions on the social reading app are, as stated by Salganik (2017), “internal states” that are better accessed when asked. \
    The survey is digitally-enhanced because both its sampling method and its interviewing process corresponds to the features of digitally-enhanced surveys described by Salganik (2017). This research uses non-probability sampling, a common and realistic sampling method in the digital era. However, according to Salganik, the difference between the target population and the frame population, and non-response produce bias. One way to enhance the result is to weigh the population who set private reading mode and the population who do not according to different rate of response.\ 
    The interviewing process of this research is also digitally-enhanced, since it is computer administered (Salganik, 2017) rather than carried out by human interviewers. Pop-ups, surveys linked to other data, WeChat Vote, and gamification all use computer software and user interface to complete the interviewing process, to collect data, and to update data. One potential drawback of the pop-ups is the cost, since WeReading’s developers will require an advertisement fee if we want to incorporate the pop-ups in their app. \
    
    <div class="pagebreak"></div>
References\

Lynch, T., & Griswold, M. (2013). Soft(a)ware in the English Classroom: Rekindling Reading: On the Use of E-readers in the English Classroom. The English Journal, 103(2), 101-104. Retrieved from http://www.jstor.org/stable/24484200 \

Salganik, Matthew J. 2017. Bit by Bit: Social Research in the Digital Age. Princeton, NJ: Princeton University Press. Open review edition.

