indexdata <- read.csv("Index.csv", header = TRUE)
library(vars)
library(lattice)
library(foreign)
library(MASS)
library(car)
require(stats)
#install.packages("stats4")#
require(stats4)
library(KernSmooth)
library(fastICA)
library(cluster)
library(leaps)
library(mgcv)
library(rpart)
library(pan)
library(mgcv)
library(DAAG)
library("TTR")
require("datasets")
require(graphics)
library("forecast")
#install.packages("astsa")
#require(astsa)
library(xtable)
# New libraries added:
library(stats)
library(TSA)
library(timeSeries)
library(fUnitRoots)
library(fBasics)
library(tseries)
library(timsac)
library(TTR)
library(fpp)
library(strucchange)
#install.packages("xts")
library(quantmod)
index <- subset(indexdata, Day == 1)
interest <- ts(index$Effective.Federal.Funds.Rate, start = c(1954, 07, 01),  freq = 12)
unemployment <- ts(index$Unemployment.Rate, start = c(1954, 07, 01), freq = 12)
ts.plot(interest, unemployment, col = c("blue", "black"), ylab = "percentage")
title(main = "Interest Rate and Unemployment Rate from 1954 to 2017")
legend("topright", c("Interest Rate", "Unemployment Rate"), col = c("blue", "black"), lty = 1)