---
title: "Research Proposal: A Study on Factors Affecting Audience Reviews of Film Adaptations"
author: "Yilun Dai"
date: "10/15/2017"
output: html_document
---

    A good plot is one of the essential factors that boost audience’s review of a film. As proven appealing stories, well-known books are usually trusted by filmmakers when it comes to developing a film. Moreover, the popularity of the book itself automatically becomes a powerful means of promotion before the film is released. However, making adaptations that cater to the audience taste is not always easy, and negative audience reviews on an adaptation will hurt the film’s market success, given how successful the original book was. Past literatures on film adaptations has focused mainly on literature review and literary analysis, and they analyze an adaptation mostly from academic and esthetic perspectives of film theorists and critics. For instance, in Facing Up to the Question of Fidelity: The Example of "A Tale of Two Cities", Brian Bialkowski examined the issue of fidelity as a tool for the critics to judge an adaptation (203), and conducted literary analysis of the presentation of the secondary character in different adaptations of Charles Dicken’s novel, A Tale of Two Cities (203). Few have utilized big data in studying the market success of a film adaptation, or have evaluated an adaptation based on audience reviews, which may or may not differ from those from the critics. Moreover, with video streaming gaining a growing share in the distribution channel of films, audience base and needs are likely to change compared to the age when theater is the major market of films. This research will use big data to examine factors contributing to positive audience reviews of film adaptations, to compare the impact of different success factors on in-theatre films and on streaming films, and to compare preferences of the audience who have read the book beforehand and those who have not read the original work before watching the film. \
    This research is going to quantify market success using data from online film reviewing databases. Two major databases that I am going to focus on will be Imdb and Rotten Tomatoes. Both are film and television reviewing database that are constantly updated with latest scores, box offices, and popularity, but each has different advantages that suit different needs and stages of this research. Using Imdb’s “Refine by Keyword” filter, I will be able to access a considerable list of films (30546 as of Oct 15th, 2017) adapted from novels using the “Based On Novel” keyword. I will extract the same list of films from Rotten Tomatoes, since Rotten Tomatoes has no similar keyword feature. Both Imdb and Rotten Tomatoes have separated reviews from users and those from critics, but users of Rotten Tomatoes can apply to become a critic if they meet certain criteria (they have two years of published reviews; they are in one of the approved critics associations, etc), making the audience review a more representative indicator for mass market success. This research will focus on audience rating and reviews. For comparing in-theater films and streaming films, I will mainly use the data from Rotten Tomatoes, since Rotten Tomatoes have a more comprehensive pool of statistics from streaming platforms, including Netflix, iTunes, Amazon Prime, and Fandango Now, while Imdb’s streaming platforms only includes Amazon Prime. I will use keywords that are relevant to “original work”, “novel”, “book”, or the author name as an identifier for audience who have read the book beforehand when comparing the preferencesof audience who were readers of the original work and those who have not read the book before watching the film.\
    Two observational methods introduced by Salganik (2017) , counting items and matching, will be used in this research. After extracting the list of films that are “Based On Novel”, I will sort them by audience ratings and number of votes, obtaining the top 25% and the bottom 25% of films. Then, using text mining, I will extract keywords from good reviews (those with 3.5 stars or higher) and bad reviews (those under 3.5 stars) and counting the frequency of occurrences. By observing the keywords with top frequencies in reviews with 3.5 stars and above and in those under 3.5 stars, I will obtain a list of potential factors that affect audience opinions on film adaptations. Then, by counting the frequencies of keywords that appear in reviews for in-theater films and those appear in reviews for streaming films, I will compare the differences in the factors that affect audience watch films from different channels. According to Salganik (2017), counting is desirable for the research when the data is big. There are 30,546 film adaptations in the database, and according to quantcast.com, there are over 3.0 million audience using Rotten Tomatoes, making the sample large enough. Counting keywords data will also be important for commercial filmmakers, so that they could take the most important factors into consideration and develop their adaptations that are more likely to achieve market success.\
    For observing how reading the original novel beforehand have impacted audience’s preferences, this research will use the matching method introduced by Salganik (2017) . First, I will create two individual rating plots, recording the ratings by those who have read the book before watching the film and those who were not readers separately, and compare the distribution. Then, I will compare the keyword occurrences in the reviews in the two groups, and this step will compare the aspects of the film are seen as important for the two groups. Salganik states that matchins is suitable when the data is always on. Imdb and Rottentomatoes are databases that are constantly updated with latest films, the fluctuations of popularity, and users are constantly adding new reviews; therefore, matching will be good for data extracted from these online film databases. \
    Another desirable characteristic of the film data used in this research is that the data is non-reactive (Salganik, 2017). Since the data is open to the public, text mining will be the major means of accessing the data. The audience will not be aware that they are being observed, and thus the research will not affect audience’s reviews. \
    Nevertheless, it should be noted that the research is restrained by some of the bad characters of the data. First, the data are likely to be non-representative. Not everyone who has watched the adaptation posts the review on film review websites; a film that receive bad audience reviews on film review websites might have succeeded in the market. However, this research cannot use the forecasting and nowcasting method, because there is no database collecting opinions from everyone who have watched the film. The closest approach will be using the past correlation between audience reviews and box office data to predict the box office performance of a new film based on a novel, but unlike the flu example demonstrated by Salganik (2017), the box office data are not lagged. Moreover, drifting (Salganik, 2017) might restrict this research. Audience who use film review databases might change overtime (a population drift according to Salganik). Another restriction of big data used in this research is that text mining might not be as clean as desired. It is likely that even after removing the stop-words, some keywords are still irrelevant to the success factors.\

<div class="pagebreak"></div>

Bialkowski, B. (2001). Facing Up to the Question of Fidelity: The Example of "A Tale of Two Cities". Literature/Film Quarterly, 29(3), 203-209. Retrieved from http://www.jstor.org/stable/43797041 \
Salganik, Matthew J. 2017. Bit by Bit: Social Research in the Digital Age. Princeton, NJ: Princeton University Press. Open review edition.



