---
title: "A Digital Field Experiment on Gay Dating App Discrimination"
author: "Kevin Sun"
date: "10/30/2017"
output: html_document
---
## Context & Background

As previously mentioned in Assignments 1 and 2, proposing an observational and survey study, respectively, Grindr was founded in 2009 as one of the first geo-social mobile networking applications or "apps." As of 2016, Grindr averages some 2.4 million daily users [1]. Grindr and the various mobile dating apps that serve the gay-male community, operate as a platform for which connections, relationships, and allyship can be built. For a historically marginalized community, the ability to openly build these connections and realize one's identity is the foundation for strengthening intracommunity solidarity and the broader LGBT community's position in regards to advocating for equity and justice. Yet, for gay men of color, race and ethnicity continue to shape power dynamics, access to resources, and visibility within the gay community. Thus, as researchers, we are interested in the answering the following questions:

#### Research Questions

- To what extent does racial and ethnic discrimination exist on gay dating platforms?
- Is there differential treatment towards people of color on gay dating apps? 

## Structure of a Computationally-Enhanced Experiment

#### Creating a Bank of Experimental Dating Profiles to Use in Digital Field Experiment

Experimental dating profiles will be constructed and posted on gay dating app platforms, like Grindr. The experimental dating profiles will be used to both, send messages to and receive messages from, real users on these dating platforms. There will be different versions of experimental dating profiles that will differ based on two components: race and profile quality. 

The race or ethnicity of the experimental dating profiles will be manipulated through random assignment under the "race" or "ethnicity" category as it appears on dating profiles: Black, Latino, Asian, White, Mixed, or no race or ethnicity will be associated with the profile. 

Additionally, the experimental profiles will vary in terms of profile quality. Profile quality will be defined by the level of detail included in the experimental profile description. Low-quality profiles will not include any description and rely solely on reported demographic information. High-quality profiles will include generic descriptions to indicate employment (IT, Sales, Government, Management, etc.), broad interests (travel, cooking, exercise, reading, etc.), and motivations for using the dating app ("looking for dates", "looking to meet interesting new people", etc.). 

Profile pictures will not be utilized on the experimental dating profiles to avoid influencing message and response rates due to users' perception of the appearance of the person in the experimental picture. Additionally, all other demographic information of profiles will be standardized; this includes: height and weight. Experimental profiles will use the National Center for Health Statistics reported average height and weight for American men: 5 feet, 9 inches and 195 pounds [2].

#### Recruiting Participants

This experiment will not need to directly "recruit" participants. The experiment will study users' interaction with and behavior towards the experimental dating profiles with the underlying assumption that users believe they are interacting with another user; this is meant to reduce reactivity. Thus, the experiment will fully be implemented the digital "field" of these online dating app platforms. Given our proximate location, users of online gay dating platforms in the city of Chicago will be participants in the experiment. We will assume that active users - those who log-on and appear on the dating app interface - are actively searching for potential partners or friends. 

#### Delivering Treatments

There will be multiple treatments in the experiment. For each racial or ethnic group (Black, Latino, Asian, White, or Mixed) a low-quality and high-quality profile will be created, for a total of 10 different treatment groups. The control group will consist of two dating profiles that do not explicitly list any race or ethnicity; one of which will be a low-quality profile and the other, a high-quality profile.

To deliver the treatments, randomly selected users in a given location will be sent a generic message ("Hey!", "How's it going?", "What's up?", etc.) from one or more of the of the experimental dating profiles. Additionally, logging-on the platform interface allows other users to send the experimental dating profiles a message as well, which we will also keep count.

Given the high levels of racial segregation in Chicago neighborhoods, treatments will be delivered in all neighborhoods of Chicago to ensure representative participation of gay male users of varying backgrounds. This will require researchers to travel to locate themselves in those neighborhoods in order to sent messages to users in that geographic area. 

#### Measuring Outcomes

We will measure whether an experimental dating profile elicits either an unsolicited response or a solicited response. An unsolicited response would be a message sent to the experimental dating profile without that experimental dating profile having previously contacted that user. A solicited response would be a user's response to a message sent by the experimental dating profile. A response to an experimental profile's message will be interpreted as an expression of interest; unless the response message is negatively worded or overtly racist, prejudiced, or biased in its wording.

Thus, we will be comparing outcomes across many measures that include, but are not limited to:

- Solicited response rates from users to experimental dating profile messages will allow us to compare solicited response rates across race and ethnicity (Example: Response rates to the White experimental dating profile vs. Black, Latino, Asian, Mixed experimental dating profiles).
- Intra-race/ethnicity response rates (Example: Asian user response rates to the Asian experimental dating profile, etc.).
- Response rates across race/ethnicity and across profile-quality (Example: White/Black/Latino/Asian/etc. user response rate to (1) low-quality White experimental dating profile, etc. VS. (2) high-quality Asian experimental dating profile, etc.)

## A Computationally-Enhanced Experiment vs. Survey or Observational Study

Under my previously proposed studies, I sought to measure the existence of explicitly expressed racist, racially prejudiced, or racially biased remarks by counting observable instances on users profile descriptions. In the proposed survey study, in an effort to capture more nuanced sentiment, as well as implicitly expressed instances of racial prejudice and bias, questions were formulated to assess user perception and experience with racism on gay dating platforms. Running a computationally-enhanced experiment yields the additional benefit of measuring not only publicly-posted expressions and self-reported perceptions/experiences, but users' actual behaviors on gay dating platforms.  

Through this digital field experiment, we approximate racially and ethnically discriminatory behavior through measuring users' response rates to experimental dating profiles that demographically differ only in the reported race/ethnicity. Given that all other demographic traits and characteristics are held constant, differences in response rates may be attributed to changing the race/ethnicity identifier of the experimental profiles. By controlling for these other demographic variables, we move closer towards identifying race as the cause for differential behavior on gay dating platforms. 

Recall that in the previous paper, we established that a survey might better evaluate peoples' internal feelings, emotions, and sentiment on an issue as complex and contentious as race, relative to an observational study. Through asking questions, researchers can obtain more nuanced responses from people who are able to expound on their profile descriptions and behaviors. Moreover, a survey, relative to an observational study, will better capture the varying experiences of white, black, latinx, Asian, etc. users on Grindr. Yet, an experiment yields key advantages over both of these methods of study.

When carried out with fidelity, reactivity on behalf of participants in the experiment will be minimal to ideally - none. Thus, the experiment may do the most thorough job in simultaneously capturing explicit and implicit racism, racial prejudice, and racial bias. An experiment of this type could pierce through the major weakness of the observational study, which is that many users will not overtly express racist and prejudice sentiment, but rather behave in their messaging or responses in racially biased manners; and those that do express such overt sentiment may be censored by the dating app administrators prior to our being able to measure those instances. Furthermore, we established social desirability bias as a potential weakness in a survey study. Users are unlikely to report their own behavior as potentially racist, prejudiced, biased, or problematic in general. An experiment carried out with fidelity could mostly avoid social desirability bias. Much like the majority of users of the internet, the majority of users on dating platforms behave as though they are not being observed; thus, an experiment that measures user behavior is likely to capture a legitimate, uncensored, un-modified, and accurate picture. 

#### Heterogeneity of Treatment Effects

Using a computationally-enhanced experiment design allows us to measure heterogeneity of treatment effects. Given the vast and diverse number of users of gay dating platforms, an experiment will allow researchers to assess how a particular treatment or treatments effect different demographic groups. With this experiment, there is potential to measure dozens of treatment effects. Recall, that with 10 different treatment groups that differ based on race/ethnicity as well as profile-quality, comparisons of sub-groups can be made.

At the broadest level, researchers could identify which race's experimental dating profile garners the highest level of solicited/unsolicited messages and responses and which racial groups garner less and by how much. More specifically, researchers might be able to differentiate response rates of of users based on their race; for example, are whites most responsive to other whites? Are other racial and ethnic groups as responsive to messages from users who share their racial/ethnic identity? Are there differences in response rates based on a users' age? Does geographic location influence response rates based on race? Will profiles of certain races garner higher response rates regardless of profile quality?

#### Casual Mechanism and Additional Challenges

While experiments provide researchers the opportunity to identify causal relationships, they are not without their challenges. This experiment too, is not without these challenges. Given that apps similar to Grindr utilize users' geographic location to determine which profiles show up on their interface, this limits the scope of the study to include users within the researcher's geographic proximity. An effort should be made to partner with researchers in varying geographic regions across the United States - including rural, suburban, and urban areas - as this would strengthen the external validity of the experiment and allow us generalize outside of the Chicago region. Of course, this brings to light additional challenges associated with the higher costs of manpower, time, and geographic reach associated with running an experiment of this size.

An additional challenge to internal validity arises when considering the dynamism of geo-social dating platforms. Relative to web-based dating sites like OK Cupid, geo-social dating apps are predicated on showing users who is near them relative to their current geographic location. Thus, the users that will show up on the platform interface, are entirely dependent on which users are in closest proximity to the researchers current location. If not controlled for, it may be possible for users to "participate" multiple times in the experiment. Hence, this may be an argument in favor of administering the experiment in geographic locations in which users are highly unlikely to overlap. 

## References

[1] Mobile app analytics: How Grindr monetizes 6 million active users (webinar). (2016, April 11). Retrieved October 19, 2017, from https://venturebeat.com/2016/04/05/mobile-app-analytics-how-grindr-monetizes-6-million-active-users-webinar/

[2] Fryar CD, Gu Q, Ogden CL, Flegal KM. Anthropometric reference data for children and adults: United States, 2011–2014. National Center for Health Statistics. Vital Health Stat 3(39). 2016.
