---
title: "Assignment 5 (Collaboration Part 3) Influenzanet"
author: "Kevin Sun"
date: "11/13/2017"
output: html_document
---

#### Note: Was not approved for Amazon exercise 

### Compare and Contrast: InfluenzaNet, Google Flu Trends, and traditional influenza tracking systems.

The effort to track the spread and predict the occurrence of influenza has resulted in the development of a variety of systems. Traditional influenza monitoring methods have relied on physicians to diagnose and report ILI (influenza-like-illness). While this historically has been the foundational method for tracking influenza, there are drawbacks. In order to capture ILI, people are required to see physicians when they are ill. Yet, we know that a variety of factors contribute to the varying rates at which people visit physicians; this includes factors such as age, access to medical services/healthcare, socio-economic status, etc. Thus, errors in capturing representative ILI information regarding the general population are inevitable. This becomes compounded with the fact that traditional systems of reporting ILI are slower given the several weeks it may take a physician to report ILI data to the Center for Disease Control (CDC) and time-consuming and potentially costly for the physicians who are required to do so. Yet, relative to the internet-based methods that will be discussed in subsequent paragraphs, traditional influenza tracking systems may include more nuanced clinical detail about patients’ illness and symptoms given direct physician measurement. 
More recently, internet-based surveillance has been undertaken to mitigate some of the weaknesses of traditional influence tracking systems. There are two broad methods of internet-based surveillance. The first method is one in which the population’s internet browsing behavior is observed and used as a proxy for measuring ILI incidence. For example, users’ search queries such as “fever” or “cough” would be measured as a proxy for assessing a population’s ILI. Google Flu Trends (GFT) is an example of this type of system. A main contrast between this method of internet-based surveillance and traditional methods is timeliness – Google Flu Trends was designed to predict CDC reports in real-time versus the usual several week lag in which CDC reports are actually released – and this was originally meant to be a strength of Google Flu Trends. Nonetheless, since GFT used internet queries as a proxy, GFT was unable to measure things such as actual levels of healthcare usage or more nuanced view on the clinical spectrum of cases. While the cost of time is lesser in using GFT, additional sources of error would include over representing those who have access to internet and are more inclined to use the internet in general – this might include younger populations and populations above a certain income level. 

A second method of internet-based surveillance is to recruit members of the public to record, using an internet-based questionnaire, specific symptoms over time. In other words, researchers would use an internet-based cohort of people to survey patterns of illness and health care attendance in these individuals. Such a design requires effort to engage the cohort. On a regular basis, people completed surveys that were several minutes in length regarding influenza symptoms. Cohort participants were also emailed newsletters with influenza information to sustain engagement. In non-pandemic years, the results from such a system seemed to be highly correlated with results from traditional surveillance methods. To mitigate errors from people who filled-out the survey as a one-off, researchers removed people who participated in survey only once. A censored sample was used, measuring participants 2nd and subsequent completions of the survey. However, the survey was not representative given that young and old people were under-sampled, women oversampled, and not all participants reported their sex. Another issue to consider is the differences in medical seeking behavior between countries. Across countries, participants varied in the amount of time between showing symptoms of illness and actually going to the doctor. Together, these issues hold potential for generating error.

Overall, internet-based surveillance lifts significant bureaucratic burden from the shoulders of physicians; and while there are overhead and manpower costs associated with implementing internet-based surveillance methods, timeliness of obtaining data remains an edge for these methods. Yet, one may argue that more nuanced clinical data is obtainable through traditional tracking systems given that doctors themselves are reporters and there is no use of a proxy measurement.

### Consider an unsettled time, such as the swine flu outbreak. Describe the possible errors in each system.

Given an unsettled time such as a swine flu outbreak, potential errors in measurement of influenza outbreak may arise in each of these systems. 
For traditional reporting systems, we can reiterate similar factors that determine the differing rates at which people are able to visit a physician. For example, access, ability, and time to see a physician is easier for non-working-class people than middle or upper-class people. Thus, unless under truly life threatening conditions, many people may simply wait for the illness to “pass-over” so to speak – this data would never be captured by traditional reporting methods. The case could also be that a person does not even identify that they have the swine flu and falsely believes they are plagued by the some other illness that is not threatening enough to see a physician for – regardless, these types of cases would not be captured through traditional reporting methods. 

For internet-based surveillance methods, we may expect to observe an over-reporting of ILI in the instance of a swine flu outbreak. This was the flaw that plagued Google Flu Trends. Given that most people are not medical professionals, many were unable to accurately diagnose themselves. When a significantly higher proportion of people simply begin to search symptom terms that are related to the flu, but not the flu itself, this caused GFT to significantly over-predict CDC estimates. 

Conversely, when there is global concern about a particular epidemic like the H1N1, there might be an over-estimation by Influenzanet as people flock to the medical professionals. Also, young children are underrepresented in Influenzanet surveys and they tend to visit the doctors more often. This could lead to under-reporting of swine flu outbreak. 
