---
title: "Exploring the GTD Data"
author: "Dan Gamarnik"
date: "November 13, 2017"
output: pdf_document
---

```{r libraries}

library(tidyverse)
library(stringr) 
library(dplyr)
library(readr)
library(ggplot2)
library(downloader)
library(tidyr)
library(broom)
library(knitr)
library(modelr)

```
#### Figure 1: Terrorism over Time
```{r GTD data}

# Getting the dataset and saving it as object.

GTD <- read_csv("globalterrorismdb_0617dist_SMALL.csv") 

# Graphing terrorist attacks over time.

na.rm=FALSE
ggplot(GTD, aes(iyear)) +
  geom_bar(fill = "red", color = "black") +
  theme_minimal() +
labs(title = "Terrorist Attacks by Year", x = "Year", y = "Attacks") 

```
#### Figure 2: Terrorism by Region
```{r GTD data 2}

# Graphing terrorist attacks by region.

na.rm=FALSE
ggplot(GTD, aes(region_txt)) +
  geom_bar(fill = "red", color = "black") +
  geom_rug() +
  scale_x_discrete() +
  coord_flip() +
  theme_minimal() +
labs(title = "Terrorist Attacks by Region", x = "Attacks (1970-2016)", y = "Region") 

```
#### Figure 3: Targets of Terrorism
```{r GTD data 3}

# Graphing terrorist targets. 

na.rm=FALSE
ggplot(GTD, aes(targtype1_txt)) +
  geom_bar(fill = "red", color = "black") +
  geom_rug() +
  scale_x_discrete() +
  coord_flip() +
  theme_minimal() +
labs(title = "Terrorist Attacks by Target", x = "Attacks (1970-2016)", y = "Target") 
```










